/*
Script Name : Generate-CollectorJob-Blocking
Category    : collectors
Purpose     : Generates DDL to create the DBA - Collect Blocking SQL Agent job.
              Creates the target database and collector.Blocking table if absent,
              then outputs T-SQL to install a recurring blocking-chain collection job.
              The job step inserts rows only when active blocking exists.
              Edit parameters, review output, then run on the target instance.
Author      : Peter Whyte (https://sqldba.blog)
Requires    : sysadmin (to run generated DDL); VIEW SERVER STATE at job runtime
Notes       : Default interval: every 2 minutes. On quiet servers the job runs but
              inserts nothing — blocking_session_id > 0 filter suppresses empty writes.
*/
-- SAFE:ReadOnly
-- IMPACT:Low
SET NOCOUNT ON;

-- ── Parameters ────────────────────────────────────────────────────────────────
DECLARE @TargetDatabase  sysname       = N'DBAMonitor';   -- created if absent
DECLARE @JobOwner        sysname       = N'sa';
DECLARE @CategoryName    nvarchar(128) = N'DBA Collectors';
DECLARE @IntervalMinutes int           = 2;
-- ─────────────────────────────────────────────────────────────────────────────

DECLARE @q       nchar(1)      = NCHAR(39);
DECLARE @crlf    nvarchar(2)   = CHAR(13) + CHAR(10);
DECLARE @ddl     nvarchar(max) = N'';
DECLARE @jobName sysname       = N'DBA - Collect Blocking';
DECLARE @stepCmd nvarchar(max);

-- ── Step command (| = single-quote placeholder) ────────────────────────────────
SET @stepCmd = REPLACE(
N'SET NOCOUNT ON;
WITH blocking_chain AS (
    SELECT
        r.session_id                AS blocked_spid,
        r.blocking_session_id       AS blocking_spid,
        r.wait_type,
        r.wait_time                 AS wait_time_ms,
        r.wait_resource,
        r.status,
        r.command,
        r.database_id,
        r.open_transaction_count,
        r.total_elapsed_time        AS elapsed_ms,
        s.login_name,
        s.host_name,
        s.program_name,
        r.sql_handle
    FROM sys.dm_exec_requests r
    JOIN sys.dm_exec_sessions s ON s.session_id = r.session_id
    WHERE r.blocking_session_id > 0
)
INSERT INTO [<<DB>>].[collector].[Blocking]
    (server_name, collection_time, blocked_spid, blocking_spid, is_head_blocker,
     wait_type, wait_time_ms, wait_resource, status, command, database_name,
     open_transaction_count, elapsed_ms, login_name, host_name, program_name,
     blocked_statement, blocker_last_statement)
SELECT
    @@SERVERNAME                                            AS server_name,
    GETDATE()                                               AS collection_time,
    bc.blocked_spid,
    bc.blocking_spid,
    CASE WHEN NOT EXISTS (
             SELECT 1 FROM sys.dm_exec_requests r2
             WHERE r2.session_id = bc.blocking_spid
               AND r2.blocking_session_id > 0)
         THEN 1 ELSE 0 END                                  AS is_head_blocker,
    bc.wait_type,
    bc.wait_time_ms,
    bc.wait_resource,
    bc.status,
    bc.command,
    DB_NAME(bc.database_id)                                 AS database_name,
    bc.open_transaction_count,
    bc.elapsed_ms,
    bc.login_name,
    bc.host_name,
    bc.program_name,
    SUBSTRING(REPLACE(REPLACE(st_blocked.text, CHAR(13), | |), CHAR(10), | |),
              (bc.blocked_spid % 128) + 1, 1000)            AS blocked_statement,
    SUBSTRING(REPLACE(REPLACE(ISNULL(st_blocker.text, |(no active request)|),
              CHAR(13), | |), CHAR(10), | |), 1, 500)       AS blocker_last_statement
FROM blocking_chain bc
OUTER APPLY sys.dm_exec_sql_text(bc.sql_handle) AS st_blocked
OUTER APPLY (
    SELECT TOP 1 st2.text
    FROM sys.dm_exec_requests r2
    OUTER APPLY sys.dm_exec_sql_text(r2.sql_handle) AS st2
    WHERE r2.session_id = bc.blocking_spid
) AS st_blocker;'
, N'|', NCHAR(39));

SET @stepCmd = REPLACE(@stepCmd, N'<<DB>>', @TargetDatabase);

-- ═══════════════════════════════════════════════════════════════════════════════
-- DDL output
-- ═══════════════════════════════════════════════════════════════════════════════
SET @ddl =
    N'-- ================================================================' + @crlf +
    N'-- Generated by Generate-CollectorJob-Blocking.sql'                  + @crlf +
    N'-- Server    : ' + @@SERVERNAME                                      + @crlf +
    N'-- Target DB : ' + @TargetDatabase                                   + @crlf +
    N'-- Generated : ' + CONVERT(nvarchar(20), GETDATE(), 120)             + @crlf +
    N'-- ================================================================' + @crlf + @crlf;

-- ── 1. Target database ────────────────────────────────────────────────────────
SET @ddl +=
    N'IF NOT EXISTS (SELECT 1 FROM sys.databases WHERE name = N' + @q + @TargetDatabase + @q + N')' + @crlf +
    N'    CREATE DATABASE [' + @TargetDatabase + N'];'                                               + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 2. Collector schema ───────────────────────────────────────────────────────
SET @ddl +=
    N'IF NOT EXISTS (SELECT 1 FROM [' + @TargetDatabase + N'].sys.schemas WHERE name = N' + @q + N'collector' + @q + N')' + @crlf +
    N'    EXEC [' + @TargetDatabase + N'].sys.sp_executesql N' + @q + N'CREATE SCHEMA collector' + @q + N';'              + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 3. Blocking table ─────────────────────────────────────────────────────────
SET @ddl +=
    N'IF NOT EXISTS (' + @crlf +
    N'    SELECT 1 FROM [' + @TargetDatabase + N'].sys.objects o'                                                                   + @crlf +
    N'    JOIN [' + @TargetDatabase + N'].sys.schemas s ON s.schema_id = o.schema_id'                                              + @crlf +
    N'    WHERE o.name = N' + @q + N'Blocking' + @q + N' AND s.name = N' + @q + N'collector' + @q + N')'                          + @crlf +
    N'CREATE TABLE [' + @TargetDatabase + N'].[collector].[Blocking] ('                                                             + @crlf +
    N'    id                      bigint IDENTITY(1,1) PRIMARY KEY,'                                                                + @crlf +
    N'    server_name             nvarchar(128) NOT NULL,'                                                                           + @crlf +
    N'    collection_time         datetime2     NOT NULL,'                                                                           + @crlf +
    N'    blocked_spid            smallint,'                                                                                         + @crlf +
    N'    blocking_spid           smallint,'                                                                                         + @crlf +
    N'    is_head_blocker         bit,'                                                                                              + @crlf +
    N'    wait_type               nvarchar(60),'                                                                                     + @crlf +
    N'    wait_time_ms            bigint,'                                                                                           + @crlf +
    N'    wait_resource           nvarchar(256),'                                                                                    + @crlf +
    N'    status                  nvarchar(30),'                                                                                     + @crlf +
    N'    command                 nvarchar(32),'                                                                                     + @crlf +
    N'    database_name           nvarchar(128),'                                                                                    + @crlf +
    N'    open_transaction_count  int,'                                                                                              + @crlf +
    N'    elapsed_ms              bigint,'                                                                                           + @crlf +
    N'    login_name              nvarchar(128),'                                                                                    + @crlf +
    N'    host_name               nvarchar(128),'                                                                                    + @crlf +
    N'    program_name            nvarchar(128),'                                                                                    + @crlf +
    N'    blocked_statement       nvarchar(1000),'                                                                                   + @crlf +
    N'    blocker_last_statement  nvarchar(500)'                                                                                     + @crlf +
    N');'                                                                                                                            + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 4. Agent category ─────────────────────────────────────────────────────────
SET @ddl +=
    N'USE msdb;' + @crlf +
    N'GO' + @crlf + @crlf +
    N'IF NOT EXISTS (SELECT 1 FROM msdb.dbo.syscategories WHERE name = N' + @q + @CategoryName + @q + N' AND category_class = 1)' + @crlf +
    N'    EXEC msdb.dbo.sp_add_category'                                                                                             + @crlf +
    N'        @class = N' + @q + N'JOB' + @q + N', @type = N' + @q + N'LOCAL' + @q + N', @name = N' + @q + @CategoryName + @q + N';' + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 5. Job + step + schedule ──────────────────────────────────────────────────
SET @ddl +=
    N'-- Job: ' + @jobName + @crlf +
    N'IF EXISTS (SELECT 1 FROM msdb.dbo.sysjobs WHERE name = N' + @q + @jobName + @q + N')'  + @crlf +
    N'    EXEC msdb.dbo.sp_delete_job @job_name = N' + @q + @jobName + @q + N', @delete_unused_schedule = 1;' + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_job'                                                                  + @crlf +
    N'    @job_name         = N' + @q + @jobName + @q + N','                                     + @crlf +
    N'    @enabled          = 1,'                                                                 + @crlf +
    N'    @owner_login_name = N' + @q + @JobOwner + @q + N','                                    + @crlf +
    N'    @category_name    = N' + @q + @CategoryName + @q + N';'                                + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_jobstep'                                                              + @crlf +
    N'    @job_name          = N' + @q + @jobName + @q + N','                                    + @crlf +
    N'    @step_id           = 1,'                                                                + @crlf +
    N'    @step_name         = N' + @q + N'Capture blocking chains' + @q + N','                  + @crlf +
    N'    @subsystem         = N' + @q + N'TSQL' + @q + N','                                     + @crlf +
    N'    @database_name     = N' + @q + N'master' + @q + N','                                   + @crlf +
    N'    @command           = N' + @q + REPLACE(@stepCmd, @q, @q + @q) + @q + N','              + @crlf +
    N'    @retry_attempts    = 0,'                                                                + @crlf +
    N'    @on_success_action = 1,'                                                                + @crlf +
    N'    @on_fail_action    = 2;'                                                                + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_schedule'                                                             + @crlf +
    N'    @schedule_name        = N' + @q + @jobName + N' Every ' + CAST(@IntervalMinutes AS nvarchar(5)) + N'min' + @q + N',' + @crlf +
    N'    @freq_type            = 4,'                                                            + @crlf +   -- daily recurring
    N'    @freq_interval        = 1,'                                                            + @crlf +
    N'    @freq_subday_type     = 4,'                                                            + @crlf +   -- minutes
    N'    @freq_subday_interval = ' + CAST(@IntervalMinutes AS nvarchar(5)) + N';'              + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_attach_schedule'                                                          + @crlf +
    N'    @job_name      = N' + @q + @jobName + @q + N','                                        + @crlf +
    N'    @schedule_name = N' + @q + @jobName + N' Every ' + CAST(@IntervalMinutes AS nvarchar(5)) + N'min' + @q + N';' + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_jobserver @job_name = N' + @q + @jobName + @q + N';'                 + @crlf +
    N'GO' + @crlf;

SELECT @ddl AS ddl;
