/*
Script Name : Generate-CollectorJob-Perfmon
Category    : collectors
Purpose     : Generates DDL to create the DBA - Collect Perfmon SQL Agent job.
              Creates the target database and collector.Perfmon table if absent,
              then outputs T-SQL to install a recurring performance counter snapshot job.
              Captures sys.dm_os_performance_counters (buffer pool, memory, throughput,
              connections, locks, plan cache). Rate counters require delta analysis.
              Edit parameters, review output, then run on the target instance.
Author      : Peter Whyte (https://sqldba.blog)
Safe        : Read-only
Impact      : Low
Requires    : sysadmin (to run generated DDL); VIEW SERVER STATE at job runtime
Notes       : Default interval: every 5 minutes.
              cntr_type column preserved: 65792 = gauge, 272696576 = cumulative rate counter.
*/
SET NOCOUNT ON;
-- SAFE:ReadOnly
-- IMPACT:Low

-- ── Parameters ────────────────────────────────────────────────────────────────
DECLARE @TargetDatabase  sysname       = N'DBAMonitor';   -- created if absent
DECLARE @JobOwner        sysname       = N'sa';
DECLARE @CategoryName    nvarchar(128) = N'DBA Collectors';
DECLARE @IntervalMinutes int           = 5;
-- ─────────────────────────────────────────────────────────────────────────────

DECLARE @q       nchar(1)      = NCHAR(39);
DECLARE @crlf    nvarchar(2)   = CHAR(13) + CHAR(10);
DECLARE @ddl     nvarchar(max) = N'';
DECLARE @jobName sysname       = N'DBA - Collect Perfmon';
DECLARE @stepCmd nvarchar(max);

-- ── Step command (| = single-quote placeholder) ────────────────────────────────
SET @stepCmd = REPLACE(
N'SET NOCOUNT ON;
INSERT INTO [<<DB>>].[collector].[Perfmon]
    (server_name, collection_time, object_name, counter_name, instance_name, cntr_value, cntr_type)
SELECT
    @@SERVERNAME                    AS server_name,
    GETDATE()                       AS collection_time,
    RTRIM(object_name)              AS object_name,
    RTRIM(counter_name)             AS counter_name,
    RTRIM(instance_name)            AS instance_name,
    cntr_value,
    cntr_type
FROM sys.dm_os_performance_counters
WHERE
    (object_name LIKE |%Buffer Manager%| AND counter_name IN (
        |Buffer cache hit ratio|, |Buffer cache hit ratio base|,
        |Page life expectancy|, |Checkpoint pages/sec|, |Lazy writes/sec|,
        |Page reads/sec|, |Page writes/sec|, |Free pages|, |Database pages|))
    OR
    (object_name LIKE |%Memory Manager%| AND counter_name IN (
        |Memory Grants Outstanding|, |Memory Grants Pending|,
        |Target Server Memory (KB)|, |Total Server Memory (KB)|,
        |Stolen Server Memory (KB)|, |Log Pool Memory (KB)|))
    OR
    (object_name LIKE |%SQL Statistics%| AND counter_name IN (
        |Batch Requests/sec|, |SQL Compilations/sec|,
        |SQL Re-Compilations/sec|, |Auto-Param Attempts/sec|))
    OR
    (object_name LIKE |%General Statistics%| AND counter_name IN (
        |User Connections|, |Logical Connections|,
        |Active Temp Tables|, |Temp Tables Creation Rate|))
    OR
    (object_name LIKE |%Locks%| AND instance_name = |_Total|
        AND counter_name IN (
            |Lock Waits/sec|, |Lock Wait Time (ms)|,
            |Number of Deadlocks/sec|, |Lock Timeouts/sec|))
    OR
    (object_name LIKE |%Databases%| AND instance_name = |_Total|
        AND counter_name IN (
            |Transactions/sec|, |Write Transactions/sec|,
            |Log Bytes Flushed/sec|, |Log Flushes/sec|, |Active Transactions|))
    OR
    (object_name LIKE |%Access Methods%| AND counter_name IN (
        |Table Lock Escalations/sec|,
        |Worktables Created/sec|, |Worktable From Cache Ratio|,
        |Worktable From Cache Base|))
    OR
    (object_name LIKE |%Plan Cache%| AND instance_name = |_Total|
        AND counter_name IN (
            |Cache Hit Ratio|, |Cache Hit Ratio Base|,
            |Cache Object Counts|, |Cache Pages|));'
, N'|', NCHAR(39));

SET @stepCmd = REPLACE(@stepCmd, N'<<DB>>', @TargetDatabase);

-- ═══════════════════════════════════════════════════════════════════════════════
-- DDL output
-- ═══════════════════════════════════════════════════════════════════════════════
SET @ddl =
    N'-- ================================================================' + @crlf +
    N'-- Generated by Generate-CollectorJob-Perfmon.sql'                   + @crlf +
    N'-- Server    : ' + @@SERVERNAME                                      + @crlf +
    N'-- Target DB : ' + @TargetDatabase                                   + @crlf +
    N'-- Generated : ' + CONVERT(nvarchar(20), GETDATE(), 120)             + @crlf +
    N'-- ================================================================' + @crlf + @crlf;

-- ── 1. Target database ────────────────────────────────────────────────────────
SET @ddl +=
    N'IF NOT EXISTS (SELECT 1 FROM sys.databases WHERE name = N' + @q + @TargetDatabase + @q + N')' + @crlf +
    N'    CREATE DATABASE [' + @TargetDatabase + N'];'                                               + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 2. Collector schema ───────────────────────────────────────────────────────
SET @ddl +=
    N'IF NOT EXISTS (SELECT 1 FROM [' + @TargetDatabase + N'].sys.schemas WHERE name = N' + @q + N'collector' + @q + N')' + @crlf +
    N'    EXEC [' + @TargetDatabase + N'].sys.sp_executesql N' + @q + N'CREATE SCHEMA collector' + @q + N';'              + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 3. Perfmon table ──────────────────────────────────────────────────────────
SET @ddl +=
    N'IF NOT EXISTS (' + @crlf +
    N'    SELECT 1 FROM [' + @TargetDatabase + N'].sys.objects o'                                                      + @crlf +
    N'    JOIN [' + @TargetDatabase + N'].sys.schemas s ON s.schema_id = o.schema_id'                                  + @crlf +
    N'    WHERE o.name = N' + @q + N'Perfmon' + @q + N' AND s.name = N' + @q + N'collector' + @q + N')'              + @crlf +
    N'CREATE TABLE [' + @TargetDatabase + N'].[collector].[Perfmon] ('                                                 + @crlf +
    N'    id              bigint IDENTITY(1,1) PRIMARY KEY,'                                                            + @crlf +
    N'    server_name     nvarchar(128) NOT NULL,'                                                                       + @crlf +
    N'    collection_time datetime2     NOT NULL,'                                                                       + @crlf +
    N'    object_name     nvarchar(128),'                                                                                + @crlf +
    N'    counter_name    nvarchar(128),'                                                                                + @crlf +
    N'    instance_name   nvarchar(128),'                                                                                + @crlf +
    N'    cntr_value      bigint,'                                                                                       + @crlf +
    N'    cntr_type       int'                                                                                           + @crlf +
    N');'                                                                                                                + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 4. Agent category ─────────────────────────────────────────────────────────
SET @ddl +=
    N'USE msdb;' + @crlf +
    N'GO' + @crlf + @crlf +
    N'IF NOT EXISTS (SELECT 1 FROM msdb.dbo.syscategories WHERE name = N' + @q + @CategoryName + @q + N' AND category_class = 1)' + @crlf +
    N'    EXEC msdb.dbo.sp_add_category'                                                                                             + @crlf +
    N'        @class = N' + @q + N'JOB' + @q + N', @type = N' + @q + N'LOCAL' + @q + N', @name = N' + @q + @CategoryName + @q + N';' + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 5. Job + step + schedule ──────────────────────────────────────────────────
SET @ddl +=
    N'-- Job: ' + @jobName + @crlf +
    N'IF EXISTS (SELECT 1 FROM msdb.dbo.sysjobs WHERE name = N' + @q + @jobName + @q + N')' + @crlf +
    N'    EXEC msdb.dbo.sp_delete_job @job_name = N' + @q + @jobName + @q + N', @delete_unused_schedule = 1;' + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_job'                                                    + @crlf +
    N'    @job_name         = N' + @q + @jobName + @q + N','                       + @crlf +
    N'    @enabled          = 1,'                                                   + @crlf +
    N'    @owner_login_name = N' + @q + @JobOwner + @q + N','                      + @crlf +
    N'    @category_name    = N' + @q + @CategoryName + @q + N';'                  + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_jobstep'                                                + @crlf +
    N'    @job_name          = N' + @q + @jobName + @q + N','                      + @crlf +
    N'    @step_id           = 1,'                                                  + @crlf +
    N'    @step_name         = N' + @q + N'Snapshot performance counters' + @q + N',' + @crlf +
    N'    @subsystem         = N' + @q + N'TSQL' + @q + N','                       + @crlf +
    N'    @database_name     = N' + @q + N'master' + @q + N','                     + @crlf +
    N'    @command           = N' + @q + REPLACE(@stepCmd, @q, @q + @q) + @q + N',' + @crlf +
    N'    @retry_attempts    = 0,'                                                  + @crlf +
    N'    @on_success_action = 1,'                                                  + @crlf +
    N'    @on_fail_action    = 2;'                                                  + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_schedule'                                               + @crlf +
    N'    @schedule_name        = N' + @q + @jobName + N' Every ' + CAST(@IntervalMinutes AS nvarchar(5)) + N'min' + @q + N',' + @crlf +
    N'    @freq_type            = 4,'                                               + @crlf +   -- daily recurring
    N'    @freq_interval        = 1,'                                               + @crlf +
    N'    @freq_subday_type     = 4,'                                               + @crlf +   -- minutes
    N'    @freq_subday_interval = ' + CAST(@IntervalMinutes AS nvarchar(5)) + N';' + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_attach_schedule'                                            + @crlf +
    N'    @job_name      = N' + @q + @jobName + @q + N','                          + @crlf +
    N'    @schedule_name = N' + @q + @jobName + N' Every ' + CAST(@IntervalMinutes AS nvarchar(5)) + N'min' + @q + N';' + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_jobserver @job_name = N' + @q + @jobName + @q + N';'   + @crlf +
    N'GO' + @crlf;

SELECT @ddl AS ddl;
