/*
Script Name : Generate-CollectorJob-AgHealth
Category    : collectors
Purpose     : Generates DDL to create the DBA - Collect AG Health SQL Agent job.
              Creates the target database and collector.AgHealth table if absent,
              then outputs T-SQL to install a recurring AG replica state snapshot job.
              On instances with no AG configured, inserts a single NO_AG sentinel row
              so the job always succeeds and the table remains queryable.
              Edit parameters, review output, then run on the target instance.
Author      : Peter Whyte (https://sqldba.blog)
Safe        : Read-only
Impact      : Low
Requires    : sysadmin (to run generated DDL); VIEW SERVER STATE at job runtime
Notes       : Default interval: every 5 minutes.
              Filter WHERE ag_name <> 'NO_AG' when querying production replica data.
*/
SET NOCOUNT ON;
-- SAFE:ReadOnly
-- IMPACT:Low

-- ── Parameters ────────────────────────────────────────────────────────────────
DECLARE @TargetDatabase  sysname       = N'DBAMonitor';   -- created if absent
DECLARE @JobOwner        sysname       = N'sa';
DECLARE @CategoryName    nvarchar(128) = N'DBA Collectors';
DECLARE @IntervalMinutes int           = 5;
-- ─────────────────────────────────────────────────────────────────────────────

DECLARE @q       nchar(1)      = NCHAR(39);
DECLARE @crlf    nvarchar(2)   = CHAR(13) + CHAR(10);
DECLARE @ddl     nvarchar(max) = N'';
DECLARE @jobName sysname       = N'DBA - Collect AG Health';
DECLARE @stepCmd nvarchar(max);

-- ── Step command (| = single-quote placeholder) ────────────────────────────────
SET @stepCmd = REPLACE(
N'SET NOCOUNT ON;
IF NOT EXISTS (SELECT 1 FROM sys.availability_groups)
BEGIN
    INSERT INTO [<<DB>>].[collector].[AgHealth]
        (server_name, collection_time, ag_name)
    VALUES (@@SERVERNAME, GETDATE(), |NO_AG|);
    RETURN;
END

INSERT INTO [<<DB>>].[collector].[AgHealth]
    (server_name, collection_time, ag_name, replica_server_name, role_desc,
     operational_state_desc, connected_state_desc, synchronization_health_desc,
     last_connect_error_description, database_name,
     db_synchronization_state_desc, db_synchronization_health_desc,
     log_send_queue_kb, log_send_rate_kb_s, redo_queue_kb, redo_rate_kb_s,
     last_sent_time, last_received_time, last_hardened_time, last_redone_time,
     last_commit_time, estimated_redo_completion_time_s, estimated_data_loss_s)
SELECT
    @@SERVERNAME                                                    AS server_name,
    GETDATE()                                                       AS collection_time,
    ag.name                                                         AS ag_name,
    ar.replica_server_name,
    ars.role_desc,
    ars.operational_state_desc,
    ars.connected_state_desc,
    ars.synchronization_health_desc,
    ars.last_connect_error_description,
    adb.database_name,
    drs.synchronization_state_desc                                  AS db_synchronization_state_desc,
    drs.synchronization_health_desc                                 AS db_synchronization_health_desc,
    drs.log_send_queue_size                                         AS log_send_queue_kb,
    drs.log_send_rate                                               AS log_send_rate_kb_s,
    drs.redo_queue_size                                             AS redo_queue_kb,
    drs.redo_rate                                                   AS redo_rate_kb_s,
    drs.last_sent_time,
    drs.last_received_time,
    drs.last_hardened_time,
    drs.last_redone_time,
    drs.last_commit_time,
    drs.estimated_redo_completion_time                              AS estimated_redo_completion_time_s,
    drs.estimated_data_loss_seconds                                 AS estimated_data_loss_s
FROM sys.availability_groups             ag
JOIN sys.availability_replicas           ar  ON ar.group_id   = ag.group_id
JOIN sys.dm_hadr_availability_replica_states ars ON ars.replica_id = ar.replica_id
LEFT JOIN sys.dm_hadr_database_replica_states drs ON drs.replica_id = ars.replica_id
LEFT JOIN sys.availability_databases_cluster adb ON adb.group_id    = ag.group_id
                                                 AND adb.group_database_id = drs.group_database_id;'
, N'|', NCHAR(39));

SET @stepCmd = REPLACE(@stepCmd, N'<<DB>>', @TargetDatabase);

-- ═══════════════════════════════════════════════════════════════════════════════
-- DDL output
-- ═══════════════════════════════════════════════════════════════════════════════
SET @ddl =
    N'-- ================================================================' + @crlf +
    N'-- Generated by Generate-CollectorJob-AgHealth.sql'                  + @crlf +
    N'-- Server    : ' + @@SERVERNAME                                      + @crlf +
    N'-- Target DB : ' + @TargetDatabase                                   + @crlf +
    N'-- Generated : ' + CONVERT(nvarchar(20), GETDATE(), 120)             + @crlf +
    N'-- ================================================================' + @crlf + @crlf;

-- ── 1. Target database ────────────────────────────────────────────────────────
SET @ddl +=
    N'IF NOT EXISTS (SELECT 1 FROM sys.databases WHERE name = N' + @q + @TargetDatabase + @q + N')' + @crlf +
    N'    CREATE DATABASE [' + @TargetDatabase + N'];'                                               + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 2. Collector schema ───────────────────────────────────────────────────────
SET @ddl +=
    N'IF NOT EXISTS (SELECT 1 FROM [' + @TargetDatabase + N'].sys.schemas WHERE name = N' + @q + N'collector' + @q + N')' + @crlf +
    N'    EXEC [' + @TargetDatabase + N'].sys.sp_executesql N' + @q + N'CREATE SCHEMA collector' + @q + N';'              + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 3. AgHealth table ─────────────────────────────────────────────────────────
SET @ddl +=
    N'IF NOT EXISTS (' + @crlf +
    N'    SELECT 1 FROM [' + @TargetDatabase + N'].sys.objects o'                                                        + @crlf +
    N'    JOIN [' + @TargetDatabase + N'].sys.schemas s ON s.schema_id = o.schema_id'                                    + @crlf +
    N'    WHERE o.name = N' + @q + N'AgHealth' + @q + N' AND s.name = N' + @q + N'collector' + @q + N')'               + @crlf +
    N'CREATE TABLE [' + @TargetDatabase + N'].[collector].[AgHealth] ('                                                  + @crlf +
    N'    id                               bigint IDENTITY(1,1) PRIMARY KEY,'                                             + @crlf +
    N'    server_name                      nvarchar(128) NOT NULL,'                                                        + @crlf +
    N'    collection_time                  datetime2     NOT NULL,'                                                        + @crlf +
    N'    ag_name                          nvarchar(128),'                                                                 + @crlf +
    N'    replica_server_name              nvarchar(256),'                                                                 + @crlf +
    N'    role_desc                        nvarchar(60),'                                                                  + @crlf +
    N'    operational_state_desc           nvarchar(60),'                                                                  + @crlf +
    N'    connected_state_desc             nvarchar(60),'                                                                  + @crlf +
    N'    synchronization_health_desc      nvarchar(60),'                                                                  + @crlf +
    N'    last_connect_error_description   nvarchar(1024),'                                                                + @crlf +
    N'    database_name                    nvarchar(128),'                                                                 + @crlf +
    N'    db_synchronization_state_desc    nvarchar(60),'                                                                  + @crlf +
    N'    db_synchronization_health_desc   nvarchar(60),'                                                                  + @crlf +
    N'    log_send_queue_kb                bigint,'                                                                        + @crlf +
    N'    log_send_rate_kb_s               bigint,'                                                                        + @crlf +
    N'    redo_queue_kb                    bigint,'                                                                        + @crlf +
    N'    redo_rate_kb_s                   bigint,'                                                                        + @crlf +
    N'    last_sent_time                   datetime2,'                                                                     + @crlf +
    N'    last_received_time               datetime2,'                                                                     + @crlf +
    N'    last_hardened_time               datetime2,'                                                                     + @crlf +
    N'    last_redone_time                 datetime2,'                                                                     + @crlf +
    N'    last_commit_time                 datetime2,'                                                                     + @crlf +
    N'    estimated_redo_completion_time_s bigint,'                                                                        + @crlf +
    N'    estimated_data_loss_s            bigint'                                                                         + @crlf +
    N');'                                                                                                                  + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 4. Agent category ─────────────────────────────────────────────────────────
SET @ddl +=
    N'USE msdb;' + @crlf +
    N'GO' + @crlf + @crlf +
    N'IF NOT EXISTS (SELECT 1 FROM msdb.dbo.syscategories WHERE name = N' + @q + @CategoryName + @q + N' AND category_class = 1)' + @crlf +
    N'    EXEC msdb.dbo.sp_add_category'                                                                                             + @crlf +
    N'        @class = N' + @q + N'JOB' + @q + N', @type = N' + @q + N'LOCAL' + @q + N', @name = N' + @q + @CategoryName + @q + N';' + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 5. Job + step + schedule ──────────────────────────────────────────────────
SET @ddl +=
    N'-- Job: ' + @jobName + @crlf +
    N'IF EXISTS (SELECT 1 FROM msdb.dbo.sysjobs WHERE name = N' + @q + @jobName + @q + N')' + @crlf +
    N'    EXEC msdb.dbo.sp_delete_job @job_name = N' + @q + @jobName + @q + N', @delete_unused_schedule = 1;' + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_job'                                                    + @crlf +
    N'    @job_name         = N' + @q + @jobName + @q + N','                       + @crlf +
    N'    @enabled          = 1,'                                                   + @crlf +
    N'    @owner_login_name = N' + @q + @JobOwner + @q + N','                      + @crlf +
    N'    @category_name    = N' + @q + @CategoryName + @q + N';'                  + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_jobstep'                                                + @crlf +
    N'    @job_name          = N' + @q + @jobName + @q + N','                      + @crlf +
    N'    @step_id           = 1,'                                                  + @crlf +
    N'    @step_name         = N' + @q + N'Snapshot AG replica state' + @q + N','  + @crlf +
    N'    @subsystem         = N' + @q + N'TSQL' + @q + N','                       + @crlf +
    N'    @database_name     = N' + @q + N'master' + @q + N','                     + @crlf +
    N'    @command           = N' + @q + REPLACE(@stepCmd, @q, @q + @q) + @q + N',' + @crlf +
    N'    @retry_attempts    = 0,'                                                  + @crlf +
    N'    @on_success_action = 1,'                                                  + @crlf +
    N'    @on_fail_action    = 2;'                                                  + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_schedule'                                               + @crlf +
    N'    @schedule_name        = N' + @q + @jobName + N' Every ' + CAST(@IntervalMinutes AS nvarchar(5)) + N'min' + @q + N',' + @crlf +
    N'    @freq_type            = 4,'                                               + @crlf +   -- daily recurring
    N'    @freq_interval        = 1,'                                               + @crlf +
    N'    @freq_subday_type     = 4,'                                               + @crlf +   -- minutes
    N'    @freq_subday_interval = ' + CAST(@IntervalMinutes AS nvarchar(5)) + N';' + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_attach_schedule'                                            + @crlf +
    N'    @job_name      = N' + @q + @jobName + @q + N','                          + @crlf +
    N'    @schedule_name = N' + @q + @jobName + N' Every ' + CAST(@IntervalMinutes AS nvarchar(5)) + N'min' + @q + N';' + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_jobserver @job_name = N' + @q + @jobName + @q + N';'   + @crlf +
    N'GO' + @crlf;

SELECT @ddl AS ddl;
