/*
Script Name : Generate-CollectorJob-DatabaseGrowth
Category    : collectors
Purpose     : Generates DDL to create the DBA - Collect Database Growth SQL Agent job.
              Creates the target database and collector.DatabaseGrowth table if absent,
              then outputs T-SQL to install a recurring database file size snapshot job.
              Each snapshot is standalone — compare file_size_mb across snapshots
              to measure growth and forecast when files will hit configured limits.
              Edit parameters, review output, then run on the target instance.
Author      : Peter Whyte (https://sqldba.blog)
Requires    : sysadmin (to run generated DDL); VIEW ANY DATABASE, VIEW DATABASE STATE at job runtime
Notes       : Default interval: every 60 minutes. growth_status flags AT_LIMIT / NEAR_LIMIT / UNLIMITED.
*/
-- SAFE:ReadOnly
-- IMPACT:Low
SET NOCOUNT ON;

-- ── Parameters ────────────────────────────────────────────────────────────────
DECLARE @TargetDatabase  sysname       = N'DBAMonitor';   -- created if absent
DECLARE @JobOwner        sysname       = N'sa';
DECLARE @CategoryName    nvarchar(128) = N'DBA Collectors';
DECLARE @IntervalMinutes int           = 60;
-- ─────────────────────────────────────────────────────────────────────────────

DECLARE @q       nchar(1)      = NCHAR(39);
DECLARE @crlf    nvarchar(2)   = CHAR(13) + CHAR(10);
DECLARE @ddl     nvarchar(max) = N'';
DECLARE @jobName sysname       = N'DBA - Collect Database Growth';
DECLARE @stepCmd nvarchar(max);

-- ── Step command (| = single-quote placeholder) ────────────────────────────────
SET @stepCmd = REPLACE(
N'SET NOCOUNT ON;
INSERT INTO [<<DB>>].[collector].[DatabaseGrowth]
    (server_name, collection_time, database_name, database_state, recovery_model_desc,
     logical_name, physical_name, file_type, file_size_mb, space_to_limit_mb,
     autogrowth, is_percent_growth, growth_limit_mb, growth_status)
SELECT
    @@SERVERNAME                                            AS server_name,
    GETDATE()                                               AS collection_time,
    d.name                                                  AS database_name,
    d.state_desc                                            AS database_state,
    d.recovery_model_desc,
    mf.name                                                 AS logical_name,
    mf.physical_name,
    mf.type_desc                                            AS file_type,
    CAST(mf.size * 8.0 / 1024 AS decimal(10,2))            AS file_size_mb,
    CASE WHEN mf.max_size IN (-1, 268435456)
         THEN NULL
         ELSE CAST((mf.max_size - mf.size) * 8.0 / 1024 AS decimal(10,2))
         END                                                AS space_to_limit_mb,
    CASE WHEN mf.is_percent_growth = 1
         THEN CAST(mf.growth AS varchar(10)) + |%|
         ELSE CAST(mf.growth * 8 / 1024 AS varchar(10)) + | MB|
         END                                                AS autogrowth,
    mf.is_percent_growth,
    CASE WHEN mf.max_size IN (-1, 268435456)
         THEN NULL
         ELSE CAST(mf.max_size * 8.0 / 1024 AS decimal(10,2))
         END                                                AS growth_limit_mb,
    CASE
        WHEN mf.max_size IN (-1, 268435456)                         THEN |UNLIMITED|
        WHEN mf.size >= mf.max_size                                 THEN |AT_LIMIT|
        WHEN (mf.max_size - mf.size) * 8.0 / 1024 < 1024
             AND mf.max_size NOT IN (-1, 268435456)                 THEN |NEAR_LIMIT|
        ELSE |OK|
    END                                                     AS growth_status
FROM sys.master_files mf
JOIN sys.databases    d  ON d.database_id = mf.database_id
WHERE d.state_desc = |ONLINE|;'
, N'|', NCHAR(39));

SET @stepCmd = REPLACE(@stepCmd, N'<<DB>>', @TargetDatabase);

-- ═══════════════════════════════════════════════════════════════════════════════
-- DDL output
-- ═══════════════════════════════════════════════════════════════════════════════
SET @ddl =
    N'-- ================================================================' + @crlf +
    N'-- Generated by Generate-CollectorJob-DatabaseGrowth.sql'            + @crlf +
    N'-- Server    : ' + @@SERVERNAME                                      + @crlf +
    N'-- Target DB : ' + @TargetDatabase                                   + @crlf +
    N'-- Generated : ' + CONVERT(nvarchar(20), GETDATE(), 120)             + @crlf +
    N'-- ================================================================' + @crlf + @crlf;

-- ── 1. Target database ────────────────────────────────────────────────────────
SET @ddl +=
    N'IF NOT EXISTS (SELECT 1 FROM sys.databases WHERE name = N' + @q + @TargetDatabase + @q + N')' + @crlf +
    N'    CREATE DATABASE [' + @TargetDatabase + N'];'                                               + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 2. Collector schema ───────────────────────────────────────────────────────
SET @ddl +=
    N'IF NOT EXISTS (SELECT 1 FROM [' + @TargetDatabase + N'].sys.schemas WHERE name = N' + @q + N'collector' + @q + N')' + @crlf +
    N'    EXEC [' + @TargetDatabase + N'].sys.sp_executesql N' + @q + N'CREATE SCHEMA collector' + @q + N';'              + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 3. DatabaseGrowth table ───────────────────────────────────────────────────
SET @ddl +=
    N'IF NOT EXISTS (' + @crlf +
    N'    SELECT 1 FROM [' + @TargetDatabase + N'].sys.objects o'                                                            + @crlf +
    N'    JOIN [' + @TargetDatabase + N'].sys.schemas s ON s.schema_id = o.schema_id'                                        + @crlf +
    N'    WHERE o.name = N' + @q + N'DatabaseGrowth' + @q + N' AND s.name = N' + @q + N'collector' + @q + N')'             + @crlf +
    N'CREATE TABLE [' + @TargetDatabase + N'].[collector].[DatabaseGrowth] ('                                                + @crlf +
    N'    id                   bigint IDENTITY(1,1) PRIMARY KEY,'                                                             + @crlf +
    N'    server_name          nvarchar(128) NOT NULL,'                                                                        + @crlf +
    N'    collection_time      datetime2     NOT NULL,'                                                                        + @crlf +
    N'    database_name        nvarchar(128),'                                                                                 + @crlf +
    N'    database_state       nvarchar(60),'                                                                                  + @crlf +
    N'    recovery_model_desc  nvarchar(60),'                                                                                  + @crlf +
    N'    logical_name         nvarchar(128),'                                                                                 + @crlf +
    N'    physical_name        nvarchar(260),'                                                                                 + @crlf +
    N'    file_type            nvarchar(60),'                                                                                  + @crlf +
    N'    file_size_mb         decimal(10,2),'                                                                                 + @crlf +
    N'    space_to_limit_mb    decimal(10,2),'                                                                                 + @crlf +
    N'    autogrowth           nvarchar(20),'                                                                                  + @crlf +
    N'    is_percent_growth    bit,'                                                                                            + @crlf +
    N'    growth_limit_mb      decimal(10,2),'                                                                                 + @crlf +
    N'    growth_status        nvarchar(20)'                                                                                   + @crlf +
    N');'                                                                                                                      + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 4. Agent category ─────────────────────────────────────────────────────────
SET @ddl +=
    N'USE msdb;' + @crlf +
    N'GO' + @crlf + @crlf +
    N'IF NOT EXISTS (SELECT 1 FROM msdb.dbo.syscategories WHERE name = N' + @q + @CategoryName + @q + N' AND category_class = 1)' + @crlf +
    N'    EXEC msdb.dbo.sp_add_category'                                                                                             + @crlf +
    N'        @class = N' + @q + N'JOB' + @q + N', @type = N' + @q + N'LOCAL' + @q + N', @name = N' + @q + @CategoryName + @q + N';' + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 5. Job + step + schedule ──────────────────────────────────────────────────
SET @ddl +=
    N'-- Job: ' + @jobName + @crlf +
    N'IF EXISTS (SELECT 1 FROM msdb.dbo.sysjobs WHERE name = N' + @q + @jobName + @q + N')' + @crlf +
    N'    EXEC msdb.dbo.sp_delete_job @job_name = N' + @q + @jobName + @q + N', @delete_unused_schedule = 1;' + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_job'                                                    + @crlf +
    N'    @job_name         = N' + @q + @jobName + @q + N','                       + @crlf +
    N'    @enabled          = 1,'                                                   + @crlf +
    N'    @owner_login_name = N' + @q + @JobOwner + @q + N','                      + @crlf +
    N'    @category_name    = N' + @q + @CategoryName + @q + N';'                  + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_jobstep'                                                + @crlf +
    N'    @job_name          = N' + @q + @jobName + @q + N','                      + @crlf +
    N'    @step_id           = 1,'                                                  + @crlf +
    N'    @step_name         = N' + @q + N'Snapshot database file sizes' + @q + N',' + @crlf +
    N'    @subsystem         = N' + @q + N'TSQL' + @q + N','                       + @crlf +
    N'    @database_name     = N' + @q + N'master' + @q + N','                     + @crlf +
    N'    @command           = N' + @q + REPLACE(@stepCmd, @q, @q + @q) + @q + N',' + @crlf +
    N'    @retry_attempts    = 0,'                                                  + @crlf +
    N'    @on_success_action = 1,'                                                  + @crlf +
    N'    @on_fail_action    = 2;'                                                  + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_schedule'                                               + @crlf +
    N'    @schedule_name        = N' + @q + @jobName + N' Every ' + CAST(@IntervalMinutes AS nvarchar(5)) + N'min' + @q + N',' + @crlf +
    N'    @freq_type            = 4,'                                               + @crlf +   -- daily recurring
    N'    @freq_interval        = 1,'                                               + @crlf +
    N'    @freq_subday_type     = 4,'                                               + @crlf +   -- minutes
    N'    @freq_subday_interval = ' + CAST(@IntervalMinutes AS nvarchar(5)) + N';' + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_attach_schedule'                                            + @crlf +
    N'    @job_name      = N' + @q + @jobName + @q + N','                          + @crlf +
    N'    @schedule_name = N' + @q + @jobName + N' Every ' + CAST(@IntervalMinutes AS nvarchar(5)) + N'min' + @q + N';' + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_jobserver @job_name = N' + @q + @jobName + @q + N';'   + @crlf +
    N'GO' + @crlf;

SELECT @ddl AS ddl;
