/*
Script Name : Generate-CollectorJob-ErrorLog
Category    : collectors
Purpose     : Generates DDL to create the DBA - Collect Error Log SQL Agent job.
              Creates the target database and collector.ErrorLog table if absent,
              then outputs T-SQL to install a recurring error log collection job.
              Each run inserts only entries newer than the latest log_date already
              stored for this server, preventing duplicate rows.
              Edit parameters, review output, then run on the target instance.
Author      : Peter Whyte (https://sqldba.blog)
Safe        : Read-only
Impact      : Low
Requires    : sysadmin (to run generated DDL); VIEW SERVER STATE, EXECUTE xp_readerrorlog at job runtime
Notes       : Default interval: every 10 minutes.
              Login succeeded and backup messages are suppressed (noisy, low signal).
*/
SET NOCOUNT ON;
-- SAFE:ReadOnly
-- IMPACT:Low

-- ── Parameters ────────────────────────────────────────────────────────────────
DECLARE @TargetDatabase  sysname       = N'DBAMonitor';   -- created if absent
DECLARE @JobOwner        sysname       = N'sa';
DECLARE @CategoryName    nvarchar(128) = N'DBA Collectors';
DECLARE @IntervalMinutes int           = 10;
-- ─────────────────────────────────────────────────────────────────────────────

DECLARE @q       nchar(1)      = NCHAR(39);
DECLARE @crlf    nvarchar(2)   = CHAR(13) + CHAR(10);
DECLARE @ddl     nvarchar(max) = N'';
DECLARE @jobName sysname       = N'DBA - Collect Error Log';
DECLARE @stepCmd nvarchar(max);

-- ── Step command (| = single-quote placeholder) ────────────────────────────────
-- @since: latest log_date already stored for this server, or 24h ago as bootstrap.
-- xp_readerrorlog is called with @since as start_time to reduce result set server-side.
-- The WHERE LogDate > @since guard handles edge case where @since matches boundary rows.
SET @stepCmd = REPLACE(
N'SET NOCOUNT ON;
DECLARE @since datetime;
SELECT @since = MAX(log_date)
FROM [<<DB>>].[collector].[ErrorLog]
WHERE server_name = @@SERVERNAME;

IF @since IS NULL
    SET @since = DATEADD(HOUR, -24, GETDATE());

CREATE TABLE #errorlog (
    LogDate     DATETIME,
    ProcessInfo NVARCHAR(100),
    Text        NVARCHAR(4000)
);

INSERT INTO #errorlog (LogDate, ProcessInfo, Text)
EXEC sys.xp_readerrorlog 0, 1, NULL, NULL, @since, NULL, N|asc|;

INSERT INTO [<<DB>>].[collector].[ErrorLog]
    (server_name, collection_time, log_date, process_info, severity, message_text)
SELECT
    @@SERVERNAME        AS server_name,
    GETDATE()           AS collection_time,
    LogDate             AS log_date,
    ProcessInfo         AS process_info,
    CASE
        WHEN Text LIKE |Error%|                                         THEN |Error|
        WHEN Text LIKE |Warning%|                                       THEN |Warning|
        WHEN Text LIKE |%severity%1[5-9]%| OR Text LIKE |%severity%2[0-4]%| THEN |Error|
        ELSE |Info|
    END                 AS severity,
    LEFT(Text, 2000)    AS message_text
FROM #errorlog
WHERE LogDate > @since
  AND Text NOT LIKE |%Login succeeded%|
  AND Text NOT LIKE |%Log was backed up%|
  AND Text NOT LIKE |BACKUP DATABASE%|
  AND Text NOT LIKE |BACKUP LOG%|
  AND LEN(LTRIM(Text)) > 0;

DROP TABLE #errorlog;'
, N'|', NCHAR(39));

SET @stepCmd = REPLACE(@stepCmd, N'<<DB>>', @TargetDatabase);

-- ═══════════════════════════════════════════════════════════════════════════════
-- DDL output
-- ═══════════════════════════════════════════════════════════════════════════════
SET @ddl =
    N'-- ================================================================' + @crlf +
    N'-- Generated by Generate-CollectorJob-ErrorLog.sql'                  + @crlf +
    N'-- Server    : ' + @@SERVERNAME                                      + @crlf +
    N'-- Target DB : ' + @TargetDatabase                                   + @crlf +
    N'-- Generated : ' + CONVERT(nvarchar(20), GETDATE(), 120)             + @crlf +
    N'-- ================================================================' + @crlf + @crlf;

-- ── 1. Target database ────────────────────────────────────────────────────────
SET @ddl +=
    N'IF NOT EXISTS (SELECT 1 FROM sys.databases WHERE name = N' + @q + @TargetDatabase + @q + N')' + @crlf +
    N'    CREATE DATABASE [' + @TargetDatabase + N'];'                                               + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 2. Collector schema ───────────────────────────────────────────────────────
SET @ddl +=
    N'IF NOT EXISTS (SELECT 1 FROM [' + @TargetDatabase + N'].sys.schemas WHERE name = N' + @q + N'collector' + @q + N')' + @crlf +
    N'    EXEC [' + @TargetDatabase + N'].sys.sp_executesql N' + @q + N'CREATE SCHEMA collector' + @q + N';'              + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 3. ErrorLog table ─────────────────────────────────────────────────────────
SET @ddl +=
    N'IF NOT EXISTS (' + @crlf +
    N'    SELECT 1 FROM [' + @TargetDatabase + N'].sys.objects o'                                                        + @crlf +
    N'    JOIN [' + @TargetDatabase + N'].sys.schemas s ON s.schema_id = o.schema_id'                                    + @crlf +
    N'    WHERE o.name = N' + @q + N'ErrorLog' + @q + N' AND s.name = N' + @q + N'collector' + @q + N')'               + @crlf +
    N'CREATE TABLE [' + @TargetDatabase + N'].[collector].[ErrorLog] ('                                                  + @crlf +
    N'    id              bigint IDENTITY(1,1) PRIMARY KEY,'                                                              + @crlf +
    N'    server_name     nvarchar(128) NOT NULL,'                                                                         + @crlf +
    N'    collection_time datetime2     NOT NULL,'                                                                         + @crlf +
    N'    log_date        datetime,'                                                                                        + @crlf +
    N'    process_info    nvarchar(100),'                                                                                   + @crlf +
    N'    severity        nvarchar(20),'                                                                                    + @crlf +
    N'    message_text    nvarchar(2000)'                                                                                   + @crlf +
    N');'                                                                                                                  + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 4. Agent category ─────────────────────────────────────────────────────────
SET @ddl +=
    N'USE msdb;' + @crlf +
    N'GO' + @crlf + @crlf +
    N'IF NOT EXISTS (SELECT 1 FROM msdb.dbo.syscategories WHERE name = N' + @q + @CategoryName + @q + N' AND category_class = 1)' + @crlf +
    N'    EXEC msdb.dbo.sp_add_category'                                                                                             + @crlf +
    N'        @class = N' + @q + N'JOB' + @q + N', @type = N' + @q + N'LOCAL' + @q + N', @name = N' + @q + @CategoryName + @q + N';' + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 5. Job + step + schedule ──────────────────────────────────────────────────
SET @ddl +=
    N'-- Job: ' + @jobName + @crlf +
    N'IF EXISTS (SELECT 1 FROM msdb.dbo.sysjobs WHERE name = N' + @q + @jobName + @q + N')' + @crlf +
    N'    EXEC msdb.dbo.sp_delete_job @job_name = N' + @q + @jobName + @q + N', @delete_unused_schedule = 1;' + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_job'                                                    + @crlf +
    N'    @job_name         = N' + @q + @jobName + @q + N','                       + @crlf +
    N'    @enabled          = 1,'                                                   + @crlf +
    N'    @owner_login_name = N' + @q + @JobOwner + @q + N','                      + @crlf +
    N'    @category_name    = N' + @q + @CategoryName + @q + N';'                  + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_jobstep'                                                + @crlf +
    N'    @job_name          = N' + @q + @jobName + @q + N','                      + @crlf +
    N'    @step_id           = 1,'                                                  + @crlf +
    N'    @step_name         = N' + @q + N'Collect new error log entries' + @q + N',' + @crlf +
    N'    @subsystem         = N' + @q + N'TSQL' + @q + N','                       + @crlf +
    N'    @database_name     = N' + @q + N'master' + @q + N','                     + @crlf +
    N'    @command           = N' + @q + REPLACE(@stepCmd, @q, @q + @q) + @q + N',' + @crlf +
    N'    @retry_attempts    = 0,'                                                  + @crlf +
    N'    @on_success_action = 1,'                                                  + @crlf +
    N'    @on_fail_action    = 2;'                                                  + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_schedule'                                               + @crlf +
    N'    @schedule_name        = N' + @q + @jobName + N' Every ' + CAST(@IntervalMinutes AS nvarchar(5)) + N'min' + @q + N',' + @crlf +
    N'    @freq_type            = 4,'                                               + @crlf +   -- daily recurring
    N'    @freq_interval        = 1,'                                               + @crlf +
    N'    @freq_subday_type     = 4,'                                               + @crlf +   -- minutes
    N'    @freq_subday_interval = ' + CAST(@IntervalMinutes AS nvarchar(5)) + N';' + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_attach_schedule'                                            + @crlf +
    N'    @job_name      = N' + @q + @jobName + @q + N','                          + @crlf +
    N'    @schedule_name = N' + @q + @jobName + N' Every ' + CAST(@IntervalMinutes AS nvarchar(5)) + N'min' + @q + N';' + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_jobserver @job_name = N' + @q + @jobName + @q + N';'   + @crlf +
    N'GO' + @crlf;

SELECT @ddl AS ddl;
