/*
Script Name : Generate-CollectorJob-StorageIO
Category    : collectors
Purpose     : Generates DDL to create the DBA - Collect Storage IO SQL Agent job.
              Creates the target database and collector.StorageIO table if absent,
              then outputs T-SQL to install a recurring I/O stats snapshot job.
              sys.dm_io_virtual_file_stats is cumulative — diff adjacent snapshots
              to measure I/O activity and latency within each collection interval.
              Edit parameters, review output, then run on the target instance.
Author      : Peter Whyte (https://sqldba.blog)
Requires    : sysadmin (to run generated DDL); VIEW SERVER STATE, VIEW DATABASE STATE at job runtime
Notes       : Default interval: every 30 minutes. sqlserver_start_time enables restart detection.
*/
-- SAFE:ReadOnly
-- IMPACT:Low
SET NOCOUNT ON;

-- ── Parameters ────────────────────────────────────────────────────────────────
DECLARE @TargetDatabase  sysname       = N'DBAMonitor';   -- created if absent
DECLARE @JobOwner        sysname       = N'sa';
DECLARE @CategoryName    nvarchar(128) = N'DBA Collectors';
DECLARE @IntervalMinutes int           = 30;
-- ─────────────────────────────────────────────────────────────────────────────

DECLARE @q       nchar(1)      = NCHAR(39);
DECLARE @crlf    nvarchar(2)   = CHAR(13) + CHAR(10);
DECLARE @ddl     nvarchar(max) = N'';
DECLARE @jobName sysname       = N'DBA - Collect Storage IO';
DECLARE @stepCmd nvarchar(max);

-- ── Step command ───────────────────────────────────────────────────────────────
SET @stepCmd =
N'SET NOCOUNT ON;
INSERT INTO [<<DB>>].[collector].[StorageIO]
    (server_name, collection_time, sqlserver_start_time, database_name, physical_name,
     file_type, database_id, file_id, num_of_reads, num_of_bytes_read, io_stall_read_ms,
     num_of_writes, num_of_bytes_written, io_stall_write_ms, io_stall,
     avg_read_latency_ms, avg_write_latency_ms, file_size_mb)
SELECT
    @@SERVERNAME                                                AS server_name,
    GETDATE()                                                   AS collection_time,
    (SELECT sqlserver_start_time FROM sys.dm_os_sys_info)       AS sqlserver_start_time,
    DB_NAME(vfs.database_id)                                    AS database_name,
    mf.physical_name,
    mf.type_desc                                                AS file_type,
    vfs.database_id,
    vfs.file_id,
    vfs.num_of_reads,
    vfs.num_of_bytes_read,
    vfs.io_stall_read_ms,
    vfs.num_of_writes,
    vfs.num_of_bytes_written,
    vfs.io_stall_write_ms,
    vfs.io_stall,
    CASE WHEN vfs.num_of_reads  > 0
         THEN CAST(vfs.io_stall_read_ms  * 1.0 / vfs.num_of_reads  AS decimal(10,2)) END AS avg_read_latency_ms,
    CASE WHEN vfs.num_of_writes > 0
         THEN CAST(vfs.io_stall_write_ms * 1.0 / vfs.num_of_writes AS decimal(10,2)) END AS avg_write_latency_ms,
    CAST(mf.size * 8.0 / 1024 AS decimal(10,2))                AS file_size_mb
FROM sys.dm_io_virtual_file_stats(NULL, NULL) vfs
JOIN sys.master_files mf
    ON mf.database_id = vfs.database_id
   AND mf.file_id     = vfs.file_id
WHERE DB_NAME(vfs.database_id) IS NOT NULL;';

SET @stepCmd = REPLACE(@stepCmd, N'<<DB>>', @TargetDatabase);

-- ═══════════════════════════════════════════════════════════════════════════════
-- DDL output
-- ═══════════════════════════════════════════════════════════════════════════════
SET @ddl =
    N'-- ================================================================' + @crlf +
    N'-- Generated by Generate-CollectorJob-StorageIO.sql'                 + @crlf +
    N'-- Server    : ' + @@SERVERNAME                                      + @crlf +
    N'-- Target DB : ' + @TargetDatabase                                   + @crlf +
    N'-- Generated : ' + CONVERT(nvarchar(20), GETDATE(), 120)             + @crlf +
    N'-- ================================================================' + @crlf + @crlf;

-- ── 1. Target database ────────────────────────────────────────────────────────
SET @ddl +=
    N'IF NOT EXISTS (SELECT 1 FROM sys.databases WHERE name = N' + @q + @TargetDatabase + @q + N')' + @crlf +
    N'    CREATE DATABASE [' + @TargetDatabase + N'];'                                               + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 2. Collector schema ───────────────────────────────────────────────────────
SET @ddl +=
    N'IF NOT EXISTS (SELECT 1 FROM [' + @TargetDatabase + N'].sys.schemas WHERE name = N' + @q + N'collector' + @q + N')' + @crlf +
    N'    EXEC [' + @TargetDatabase + N'].sys.sp_executesql N' + @q + N'CREATE SCHEMA collector' + @q + N';'              + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 3. StorageIO table ────────────────────────────────────────────────────────
SET @ddl +=
    N'IF NOT EXISTS (' + @crlf +
    N'    SELECT 1 FROM [' + @TargetDatabase + N'].sys.objects o'                                                        + @crlf +
    N'    JOIN [' + @TargetDatabase + N'].sys.schemas s ON s.schema_id = o.schema_id'                                    + @crlf +
    N'    WHERE o.name = N' + @q + N'StorageIO' + @q + N' AND s.name = N' + @q + N'collector' + @q + N')'              + @crlf +
    N'CREATE TABLE [' + @TargetDatabase + N'].[collector].[StorageIO] ('                                                 + @crlf +
    N'    id                    bigint IDENTITY(1,1) PRIMARY KEY,'                                                        + @crlf +
    N'    server_name           nvarchar(128) NOT NULL,'                                                                   + @crlf +
    N'    collection_time       datetime2     NOT NULL,'                                                                   + @crlf +
    N'    sqlserver_start_time  datetime2,'                                                                                + @crlf +
    N'    database_name         nvarchar(128),'                                                                            + @crlf +
    N'    physical_name         nvarchar(260),'                                                                            + @crlf +
    N'    file_type             nvarchar(60),'                                                                             + @crlf +
    N'    database_id           int,'                                                                                      + @crlf +
    N'    file_id               int,'                                                                                      + @crlf +
    N'    num_of_reads          bigint,'                                                                                   + @crlf +
    N'    num_of_bytes_read     bigint,'                                                                                   + @crlf +
    N'    io_stall_read_ms      bigint,'                                                                                   + @crlf +
    N'    num_of_writes         bigint,'                                                                                   + @crlf +
    N'    num_of_bytes_written  bigint,'                                                                                   + @crlf +
    N'    io_stall_write_ms     bigint,'                                                                                   + @crlf +
    N'    io_stall              bigint,'                                                                                   + @crlf +
    N'    avg_read_latency_ms   decimal(10,2),'                                                                            + @crlf +
    N'    avg_write_latency_ms  decimal(10,2),'                                                                            + @crlf +
    N'    file_size_mb          decimal(10,2)'                                                                             + @crlf +
    N');'                                                                                                                  + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 4. Agent category ─────────────────────────────────────────────────────────
SET @ddl +=
    N'USE msdb;' + @crlf +
    N'GO' + @crlf + @crlf +
    N'IF NOT EXISTS (SELECT 1 FROM msdb.dbo.syscategories WHERE name = N' + @q + @CategoryName + @q + N' AND category_class = 1)' + @crlf +
    N'    EXEC msdb.dbo.sp_add_category'                                                                                             + @crlf +
    N'        @class = N' + @q + N'JOB' + @q + N', @type = N' + @q + N'LOCAL' + @q + N', @name = N' + @q + @CategoryName + @q + N';' + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 5. Job + step + schedule ──────────────────────────────────────────────────
SET @ddl +=
    N'-- Job: ' + @jobName + @crlf +
    N'IF EXISTS (SELECT 1 FROM msdb.dbo.sysjobs WHERE name = N' + @q + @jobName + @q + N')' + @crlf +
    N'    EXEC msdb.dbo.sp_delete_job @job_name = N' + @q + @jobName + @q + N', @delete_unused_schedule = 1;' + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_job'                                                    + @crlf +
    N'    @job_name         = N' + @q + @jobName + @q + N','                       + @crlf +
    N'    @enabled          = 1,'                                                   + @crlf +
    N'    @owner_login_name = N' + @q + @JobOwner + @q + N','                      + @crlf +
    N'    @category_name    = N' + @q + @CategoryName + @q + N';'                  + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_jobstep'                                                + @crlf +
    N'    @job_name          = N' + @q + @jobName + @q + N','                      + @crlf +
    N'    @step_id           = 1,'                                                  + @crlf +
    N'    @step_name         = N' + @q + N'Snapshot file I/O stats' + @q + N','   + @crlf +
    N'    @subsystem         = N' + @q + N'TSQL' + @q + N','                       + @crlf +
    N'    @database_name     = N' + @q + N'master' + @q + N','                     + @crlf +
    N'    @command           = N' + @q + REPLACE(@stepCmd, @q, @q + @q) + @q + N',' + @crlf +
    N'    @retry_attempts    = 0,'                                                  + @crlf +
    N'    @on_success_action = 1,'                                                  + @crlf +
    N'    @on_fail_action    = 2;'                                                  + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_schedule'                                               + @crlf +
    N'    @schedule_name        = N' + @q + @jobName + N' Every ' + CAST(@IntervalMinutes AS nvarchar(5)) + N'min' + @q + N',' + @crlf +
    N'    @freq_type            = 4,'                                               + @crlf +   -- daily recurring
    N'    @freq_interval        = 1,'                                               + @crlf +
    N'    @freq_subday_type     = 4,'                                               + @crlf +   -- minutes
    N'    @freq_subday_interval = ' + CAST(@IntervalMinutes AS nvarchar(5)) + N';' + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_attach_schedule'                                            + @crlf +
    N'    @job_name      = N' + @q + @jobName + @q + N','                          + @crlf +
    N'    @schedule_name = N' + @q + @jobName + N' Every ' + CAST(@IntervalMinutes AS nvarchar(5)) + N'min' + @q + N';' + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_jobserver @job_name = N' + @q + @jobName + @q + N';'   + @crlf +
    N'GO' + @crlf;

SELECT @ddl AS ddl;
