/*
Script Name : Generate-CollectorJob-VlfCount
Category    : collectors
Purpose     : Generates DDL to create the DBA - Collect VLF Count SQL Agent job.
              Creates the target database and a system-versioned (temporal) collector table
              if absent, then outputs T-SQL to install a daily VLF count MERGE job.
              Each run upserts current VLF counts per database — SQL Server automatically
              records every change in the paired history table, capturing exactly when
              VLF counts spiked (autogrowth) or dropped (log maintenance).
              Edit parameters, review output, then run on the target instance.
Author      : Peter Whyte (https://sqldba.blog)
Requires    : sysadmin (to run generated DDL); VIEW SERVER STATE, VIEW DATABASE STATE at job runtime
Notes       : Default schedule: daily at 02:00. Requires SQL Server 2016+ (sys.dm_db_log_info).
              Thresholds: <100 OK, 100-999 MONITOR, 1000+ WARNING, 10000+ CRITICAL.
              If upgrading from the non-temporal version, drop collector.VlfCount manually first.
*/
-- SAFE:ReadOnly
-- IMPACT:Low
SET NOCOUNT ON;

-- ── Parameters ────────────────────────────────────────────────────────────────
DECLARE @TargetDatabase  sysname  = N'DBAMonitor';
DECLARE @JobOwner        sysname  = N'sa';
DECLARE @CategoryName    nvarchar(128) = N'DBA Collectors';
DECLARE @RunHour         tinyint  = 2;
-- ─────────────────────────────────────────────────────────────────────────────

DECLARE @q        nchar(1)      = NCHAR(39);
DECLARE @crlf     nvarchar(2)   = CHAR(13) + CHAR(10);
DECLARE @ddl      nvarchar(max) = N'';
DECLARE @jobName  sysname       = N'DBA - Collect VLF Count';
DECLARE @schedTS  int           = @RunHour * 10000;
DECLARE @stepCmd  nvarchar(max);

-- ── Step command (| = single-quote placeholder) ────────────────────────────────
SET @stepCmd = REPLACE(
N'SET NOCOUNT ON;
MERGE [<<DB>>].[collector].[VlfCountCurrent] AS target
USING (
    SELECT
        @@SERVERNAME                                        AS server_name,
        d.name                                              AS database_name,
        d.recovery_model_desc,
        d.log_reuse_wait_desc,
        COUNT(li.file_id)                                   AS vlf_count,
        CAST(mf.size * 8.0 / 1024 AS decimal(10,2))        AS log_file_size_mb,
        CASE
            WHEN COUNT(li.file_id) >= 10000 THEN |CRITICAL|
            WHEN COUNT(li.file_id) >= 1000  THEN |WARNING|
            WHEN COUNT(li.file_id) >= 100   THEN |MONITOR|
            ELSE |OK|
        END                                                 AS vlf_status
    FROM sys.databases d
    JOIN sys.master_files mf
        ON mf.database_id = d.database_id
       AND mf.type = 1
    CROSS APPLY sys.dm_db_log_info(d.database_id) li
    WHERE d.state_desc = |ONLINE|
      AND d.database_id > 4
    GROUP BY d.name, d.recovery_model_desc, d.log_reuse_wait_desc, mf.size
) AS source
ON  target.server_name   = source.server_name
AND target.database_name = source.database_name
WHEN MATCHED AND (
    target.vlf_count    <> source.vlf_count    OR
    target.vlf_status   <> source.vlf_status   OR
    ISNULL(target.log_reuse_wait_desc, |_|) <> ISNULL(source.log_reuse_wait_desc, |_|)
) THEN UPDATE SET
    recovery_model_desc  = source.recovery_model_desc,
    log_reuse_wait_desc  = source.log_reuse_wait_desc,
    vlf_count            = source.vlf_count,
    log_file_size_mb     = source.log_file_size_mb,
    vlf_status           = source.vlf_status
WHEN NOT MATCHED BY TARGET THEN
    INSERT (server_name, database_name, recovery_model_desc, log_reuse_wait_desc,
            vlf_count, log_file_size_mb, vlf_status)
    VALUES (source.server_name, source.database_name, source.recovery_model_desc,
            source.log_reuse_wait_desc, source.vlf_count, source.log_file_size_mb,
            source.vlf_status);'
, N'|', NCHAR(39));

SET @stepCmd = REPLACE(@stepCmd, N'<<DB>>', @TargetDatabase);

-- ═══════════════════════════════════════════════════════════════════════════════
-- DDL output
-- ═══════════════════════════════════════════════════════════════════════════════
SET @ddl =
    N'-- ================================================================' + @crlf +
    N'-- Generated by Generate-CollectorJob-VlfCount.sql'                  + @crlf +
    N'-- Server    : ' + @@SERVERNAME                                      + @crlf +
    N'-- Target DB : ' + @TargetDatabase                                   + @crlf +
    N'-- Generated : ' + CONVERT(nvarchar(20), GETDATE(), 120)             + @crlf +
    N'-- ================================================================' + @crlf + @crlf;

-- ── 1. Target database ────────────────────────────────────────────────────────
SET @ddl +=
    N'IF NOT EXISTS (SELECT 1 FROM sys.databases WHERE name = N' + @q + @TargetDatabase + @q + N')' + @crlf +
    N'    CREATE DATABASE [' + @TargetDatabase + N'];'                                               + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 2. Collector schema ───────────────────────────────────────────────────────
SET @ddl +=
    N'IF NOT EXISTS (SELECT 1 FROM [' + @TargetDatabase + N'].sys.schemas WHERE name = N' + @q + N'collector' + @q + N')' + @crlf +
    N'    EXEC [' + @TargetDatabase + N'].sys.sp_executesql N' + @q + N'CREATE SCHEMA collector' + @q + N';'              + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 3. VlfCountCurrent temporal table ─────────────────────────────────────────
SET @ddl +=
    N'IF NOT EXISTS (' + @crlf +
    N'    SELECT 1 FROM [' + @TargetDatabase + N'].sys.objects o'                                                              + @crlf +
    N'    JOIN [' + @TargetDatabase + N'].sys.schemas s ON s.schema_id = o.schema_id'                                          + @crlf +
    N'    WHERE o.name = N' + @q + N'VlfCountCurrent' + @q + N' AND s.name = N' + @q + N'collector' + @q + N')'              + @crlf +
    N'BEGIN' + @crlf +
    N'CREATE TABLE [' + @TargetDatabase + N'].[collector].[VlfCountCurrent] ('                 + @crlf +
    N'    server_name          nvarchar(128)  NOT NULL,'                                        + @crlf +
    N'    database_name        nvarchar(128)  NOT NULL,'                                        + @crlf +
    N'    recovery_model_desc  nvarchar(60)   NULL,'                                            + @crlf +
    N'    log_reuse_wait_desc  nvarchar(60)   NULL,'                                            + @crlf +
    N'    vlf_count            int            NULL,'                                            + @crlf +
    N'    log_file_size_mb     decimal(10,2)  NULL,'                                            + @crlf +
    N'    vlf_status           nvarchar(20)   NULL,'                                            + @crlf +
    N'    SysStartTime         datetime2(2)   GENERATED ALWAYS AS ROW START NOT NULL,'         + @crlf +
    N'    SysEndTime           datetime2(2)   GENERATED ALWAYS AS ROW END   NOT NULL,'         + @crlf +
    N'    PERIOD FOR SYSTEM_TIME (SysStartTime, SysEndTime),'                                  + @crlf +
    N'    CONSTRAINT [PK_VlfCountCurrent]'                                                     + @crlf +
    N'        PRIMARY KEY (server_name, database_name)'                                        + @crlf +
    N') WITH (SYSTEM_VERSIONING = ON ('                                                        + @crlf +
    N'    HISTORY_TABLE        = [collector].[VlfCountHistory],'                               + @crlf +
    N'    DATA_CONSISTENCY_CHECK = ON));'                                                       + @crlf +
    N'END' + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 4. Agent category ─────────────────────────────────────────────────────────
SET @ddl +=
    N'USE msdb;' + @crlf +
    N'GO' + @crlf + @crlf +
    N'IF NOT EXISTS (SELECT 1 FROM msdb.dbo.syscategories WHERE name = N' + @q + @CategoryName + @q + N' AND category_class = 1)' + @crlf +
    N'    EXEC msdb.dbo.sp_add_category'                                                                                             + @crlf +
    N'        @class = N' + @q + N'JOB' + @q + N', @type = N' + @q + N'LOCAL' + @q + N', @name = N' + @q + @CategoryName + @q + N';' + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 5. Job + step + schedule ──────────────────────────────────────────────────
SET @ddl +=
    N'-- Job: ' + @jobName + @crlf +
    N'IF EXISTS (SELECT 1 FROM msdb.dbo.sysjobs WHERE name = N' + @q + @jobName + @q + N')' + @crlf +
    N'    EXEC msdb.dbo.sp_delete_job @job_name = N' + @q + @jobName + @q + N', @delete_unused_schedule = 1;' + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_job'                                                    + @crlf +
    N'    @job_name         = N' + @q + @jobName + @q + N','                       + @crlf +
    N'    @enabled          = 1,'                                                   + @crlf +
    N'    @owner_login_name = N' + @q + @JobOwner + @q + N','                      + @crlf +
    N'    @category_name    = N' + @q + @CategoryName + @q + N';'                  + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_jobstep'                                                + @crlf +
    N'    @job_name          = N' + @q + @jobName + @q + N','                      + @crlf +
    N'    @step_id           = 1,'                                                  + @crlf +
    N'    @step_name         = N' + @q + N'Merge VLF counts' + @q + N','           + @crlf +
    N'    @subsystem         = N' + @q + N'TSQL' + @q + N','                       + @crlf +
    N'    @database_name     = N' + @q + N'master' + @q + N','                     + @crlf +
    N'    @command           = N' + @q + REPLACE(@stepCmd, @q, @q + @q) + @q + N',' + @crlf +
    N'    @retry_attempts    = 0,'                                                  + @crlf +
    N'    @on_success_action = 1,'                                                  + @crlf +
    N'    @on_fail_action    = 2;'                                                  + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_schedule'                                               + @crlf +
    N'    @schedule_name          = N' + @q + @jobName + N' Daily ' + CAST(@RunHour AS nvarchar(2)) + N':00' + @q + N',' + @crlf +
    N'    @freq_type              = 4,'                                             + @crlf +
    N'    @freq_interval          = 1,'                                             + @crlf +
    N'    @freq_subday_type       = 1,'                                             + @crlf +
    N'    @active_start_time      = ' + CAST(@schedTS AS nvarchar(10)) + N';'      + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_attach_schedule'                                            + @crlf +
    N'    @job_name      = N' + @q + @jobName + @q + N','                          + @crlf +
    N'    @schedule_name = N' + @q + @jobName + N' Daily ' + CAST(@RunHour AS nvarchar(2)) + N':00' + @q + N';' + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_jobserver @job_name = N' + @q + @jobName + @q + N';'   + @crlf +
    N'GO' + @crlf;

SELECT @ddl AS ddl;
