/*
Script Name : Generate-CollectorJob-WaitStats
Category    : collectors
Purpose     : Generates DDL to create the DBA - Collect Wait Stats SQL Agent job.
              Creates the target database and collector.WaitStats table if absent,
              then outputs T-SQL to install a recurring wait stats snapshot job.
              sys.dm_os_wait_stats is cumulative — diff adjacent snapshots for interval rates.
              Edit parameters, review output, then run on the target instance.
Author      : Peter Whyte (https://sqldba.blog)
Safe        : Read-only
Impact      : Low
Requires    : sysadmin (to run generated DDL); VIEW SERVER STATE at job runtime
Notes       : Default interval: every 15 minutes. Each run appends one snapshot batch.
              sqlserver_start_time column enables restart detection in delta analysis.
*/
SET NOCOUNT ON;
-- SAFE:ReadOnly
-- IMPACT:Low

-- ── Parameters ────────────────────────────────────────────────────────────────
DECLARE @TargetDatabase  sysname       = N'DBAMonitor';   -- created if absent
DECLARE @JobOwner        sysname       = N'sa';
DECLARE @CategoryName    nvarchar(128) = N'DBA Collectors';
DECLARE @IntervalMinutes int           = 15;
-- ─────────────────────────────────────────────────────────────────────────────

DECLARE @q       nchar(1)      = NCHAR(39);
DECLARE @crlf    nvarchar(2)   = CHAR(13) + CHAR(10);
DECLARE @ddl     nvarchar(max) = N'';
DECLARE @jobName sysname       = N'DBA - Collect Wait Stats';
DECLARE @stepCmd nvarchar(max);

-- ── Step command ───────────────────────────────────────────────────────────────
SET @stepCmd =
N'SET NOCOUNT ON;
INSERT INTO [<<DB>>].[collector].[WaitStats]
    (server_name, collection_time, sqlserver_start_time, wait_type,
     waiting_tasks_count, wait_time_ms, max_wait_time_ms,
     signal_wait_time_ms, resource_wait_time_ms)
SELECT
    @@SERVERNAME                                            AS server_name,
    GETDATE()                                               AS collection_time,
    (SELECT sqlserver_start_time FROM sys.dm_os_sys_info)   AS sqlserver_start_time,
    wait_type,
    waiting_tasks_count,
    wait_time_ms,
    max_wait_time_ms,
    signal_wait_time_ms,
    wait_time_ms - signal_wait_time_ms                      AS resource_wait_time_ms
FROM sys.dm_os_wait_stats
WHERE waiting_tasks_count > 0
  AND wait_type NOT IN (
      N''SLEEP_TASK'',                  N''SLEEP_SYSTEMTASK'',
      N''SLEEP_TEMPDBSTARTUP'',         N''SLEEP_DBSTARTUP'',
      N''SLEEP_DCOMSTARTUP'',           N''SLEEP_MASTERDBREADY'',
      N''SLEEP_MASTERMDREADY'',         N''SLEEP_MASTERUPGRADED'',
      N''SLEEP_MSDBSTARTUP'',           N''SNI_HTTP_ACCEPT'',
      N''DISPATCHER_QUEUE_SEMAPHORE'',  N''BROKER_TO_FLUSH'',
      N''BROKER_TASK_STOP'',            N''BROKER_EVENTHANDLER'',
      N''BROKER_RECEIVE_WAITFOR'',      N''CHECKPOINT_QUEUE'',
      N''DBMIRROR_EVENTS_QUEUE'',       N''DBMIRROR_WORKER_QUEUE'',
      N''SQLTRACE_INCREMENTAL_FLUSH_SLEEP'', N''SQLTRACE_BUFFER_FLUSH'',
      N''SQLTRACE_WAIT_ENTRIES'',       N''WAITFOR'',
      N''LAZYWRITER_SLEEP'',            N''LOGMGR_QUEUE'',
      N''ONDEMAND_TASK_QUEUE'',         N''REQUEST_FOR_DEADLOCK_SEARCH'',
      N''RESOURCE_QUEUE'',              N''SERVER_IDLE_CHECK'',
      N''SP_SERVER_DIAGNOSTICS_SLEEP'', N''WAIT_XTP_OFFLINE_CKPT_NEW_LOG'',
      N''XE_DISPATCHER_WAIT'',          N''XE_TIMER_EVENT'',
      N''HADR_WORK_QUEUE'',             N''HADR_FILESTREAM_IOMGR_IOCOMPLETION'',
      N''HADR_CLUSAPI_CALL'',           N''HADR_NOTIFICATION_DEQUEUE'',
      N''FT_IFTS_SCHEDULER_IDLE_WAIT'', N''FT_IFTSHC_MUTEX'',
      N''REPL_WORK_QUEUE'',             N''CLR_AUTO_EVENT'',
      N''CLR_MANUAL_EVENT'',            N''WAIT_XTP_COMPILE_WAIT''
  );';

SET @stepCmd = REPLACE(@stepCmd, N'<<DB>>', @TargetDatabase);

-- ═══════════════════════════════════════════════════════════════════════════════
-- DDL output
-- ═══════════════════════════════════════════════════════════════════════════════
SET @ddl =
    N'-- ================================================================' + @crlf +
    N'-- Generated by Generate-CollectorJob-WaitStats.sql'                 + @crlf +
    N'-- Server    : ' + @@SERVERNAME                                      + @crlf +
    N'-- Target DB : ' + @TargetDatabase                                   + @crlf +
    N'-- Generated : ' + CONVERT(nvarchar(20), GETDATE(), 120)             + @crlf +
    N'-- ================================================================' + @crlf + @crlf;

-- ── 1. Target database ────────────────────────────────────────────────────────
SET @ddl +=
    N'IF NOT EXISTS (SELECT 1 FROM sys.databases WHERE name = N' + @q + @TargetDatabase + @q + N')' + @crlf +
    N'    CREATE DATABASE [' + @TargetDatabase + N'];'                                               + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 2. Collector schema ───────────────────────────────────────────────────────
SET @ddl +=
    N'IF NOT EXISTS (SELECT 1 FROM [' + @TargetDatabase + N'].sys.schemas WHERE name = N' + @q + N'collector' + @q + N')' + @crlf +
    N'    EXEC [' + @TargetDatabase + N'].sys.sp_executesql N' + @q + N'CREATE SCHEMA collector' + @q + N';'              + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 3. WaitStats table ────────────────────────────────────────────────────────
SET @ddl +=
    N'IF NOT EXISTS (' + @crlf +
    N'    SELECT 1 FROM [' + @TargetDatabase + N'].sys.objects o'                                                       + @crlf +
    N'    JOIN [' + @TargetDatabase + N'].sys.schemas s ON s.schema_id = o.schema_id'                                   + @crlf +
    N'    WHERE o.name = N' + @q + N'WaitStats' + @q + N' AND s.name = N' + @q + N'collector' + @q + N')'              + @crlf +
    N'CREATE TABLE [' + @TargetDatabase + N'].[collector].[WaitStats] ('                                                + @crlf +
    N'    id                    bigint IDENTITY(1,1) PRIMARY KEY,'                                                       + @crlf +
    N'    server_name           nvarchar(128) NOT NULL,'                                                                  + @crlf +
    N'    collection_time       datetime2     NOT NULL,'                                                                  + @crlf +
    N'    sqlserver_start_time  datetime2,'                                                                               + @crlf +
    N'    wait_type             nvarchar(60)  NOT NULL,'                                                                  + @crlf +
    N'    waiting_tasks_count   bigint,'                                                                                  + @crlf +
    N'    wait_time_ms          bigint,'                                                                                  + @crlf +
    N'    max_wait_time_ms      bigint,'                                                                                  + @crlf +
    N'    signal_wait_time_ms   bigint,'                                                                                  + @crlf +
    N'    resource_wait_time_ms bigint'                                                                                   + @crlf +
    N');'                                                                                                                 + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 4. Agent category ─────────────────────────────────────────────────────────
SET @ddl +=
    N'USE msdb;' + @crlf +
    N'GO' + @crlf + @crlf +
    N'IF NOT EXISTS (SELECT 1 FROM msdb.dbo.syscategories WHERE name = N' + @q + @CategoryName + @q + N' AND category_class = 1)' + @crlf +
    N'    EXEC msdb.dbo.sp_add_category'                                                                                             + @crlf +
    N'        @class = N' + @q + N'JOB' + @q + N', @type = N' + @q + N'LOCAL' + @q + N', @name = N' + @q + @CategoryName + @q + N';' + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 5. Job + step + schedule ──────────────────────────────────────────────────
SET @ddl +=
    N'-- Job: ' + @jobName + @crlf +
    N'IF EXISTS (SELECT 1 FROM msdb.dbo.sysjobs WHERE name = N' + @q + @jobName + @q + N')' + @crlf +
    N'    EXEC msdb.dbo.sp_delete_job @job_name = N' + @q + @jobName + @q + N', @delete_unused_schedule = 1;' + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_job'                                                    + @crlf +
    N'    @job_name         = N' + @q + @jobName + @q + N','                       + @crlf +
    N'    @enabled          = 1,'                                                   + @crlf +
    N'    @owner_login_name = N' + @q + @JobOwner + @q + N','                      + @crlf +
    N'    @category_name    = N' + @q + @CategoryName + @q + N';'                  + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_jobstep'                                                + @crlf +
    N'    @job_name          = N' + @q + @jobName + @q + N','                      + @crlf +
    N'    @step_id           = 1,'                                                  + @crlf +
    N'    @step_name         = N' + @q + N'Snapshot wait stats' + @q + N','        + @crlf +
    N'    @subsystem         = N' + @q + N'TSQL' + @q + N','                       + @crlf +
    N'    @database_name     = N' + @q + N'master' + @q + N','                     + @crlf +
    N'    @command           = N' + @q + REPLACE(@stepCmd, @q, @q + @q) + @q + N',' + @crlf +
    N'    @retry_attempts    = 0,'                                                  + @crlf +
    N'    @on_success_action = 1,'                                                  + @crlf +
    N'    @on_fail_action    = 2;'                                                  + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_schedule'                                               + @crlf +
    N'    @schedule_name        = N' + @q + @jobName + N' Every ' + CAST(@IntervalMinutes AS nvarchar(5)) + N'min' + @q + N',' + @crlf +
    N'    @freq_type            = 4,'                                               + @crlf +   -- daily recurring
    N'    @freq_interval        = 1,'                                               + @crlf +
    N'    @freq_subday_type     = 4,'                                               + @crlf +   -- minutes
    N'    @freq_subday_interval = ' + CAST(@IntervalMinutes AS nvarchar(5)) + N';' + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_attach_schedule'                                            + @crlf +
    N'    @job_name      = N' + @q + @jobName + @q + N','                          + @crlf +
    N'    @schedule_name = N' + @q + @jobName + N' Every ' + CAST(@IntervalMinutes AS nvarchar(5)) + N'min' + @q + N';' + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_jobserver @job_name = N' + @q + @jobName + @q + N';'   + @crlf +
    N'GO' + @crlf;

SELECT @ddl AS ddl;
