/*
Script Name : Generate-CollectorJob-IndexFragmentation
Category    : collectors
Purpose     : Generates DDL to create the DBA - Collect Index Fragmentation SQL Agent job.
              Creates the target database and collector.IndexFragmentation table if absent,
              then outputs T-SQL to install a weekly index fragmentation snapshot job.
              The job iterates all online user databases using SAMPLED mode
              (reads ~1% of pages — accurate for detection, avoids DETAILED overhead).
              Indexes smaller than 100 pages and heaps are excluded.
              Edit parameters, review output, then run on the target instance.
Author      : Peter Whyte (https://sqldba.blog)
Safe        : Read-only
Impact      : Low — SAMPLED mode; avoid scheduling during peak hours
Requires    : sysadmin (to run generated DDL); VIEW DATABASE STATE per database at job runtime
Notes       : Default schedule: weekly, Saturday at 01:00.
              Thresholds: >=30% REBUILD, 10-29% REORGANIZE, <10% NONE.
*/
SET NOCOUNT ON;
-- SAFE:ReadOnly
-- IMPACT:Low

-- ── Parameters ────────────────────────────────────────────────────────────────
DECLARE @TargetDatabase  sysname       = N'DBAMonitor';   -- created if absent
DECLARE @JobOwner        sysname       = N'sa';
DECLARE @CategoryName    nvarchar(128) = N'DBA Collectors';
DECLARE @RunHour         tinyint       = 1;               -- hour (0-23) for weekly run
-- ─────────────────────────────────────────────────────────────────────────────

DECLARE @q        nchar(1)      = NCHAR(39);
DECLARE @crlf     nvarchar(2)   = CHAR(13) + CHAR(10);
DECLARE @ddl      nvarchar(max) = N'';
DECLARE @jobName  sysname       = N'DBA - Collect Index Fragmentation';
DECLARE @schedTS  int           = @RunHour * 10000;
DECLARE @stepCmd  nvarchar(max);

-- ── Step command (| = single-quote placeholder) ────────────────────────────────
-- Builds @sql via string concatenation so @db is evaluated, not embedded literally.
-- @dbid (integer DB_ID) is computed before @sql is built, avoiding embedded string quotes
-- for the DB name inside the DMV call.
-- N|...|  segments become N'...' after REPLACE; || inside them → '' (escaped quote).
SET @stepCmd = REPLACE(
N'SET NOCOUNT ON;
DECLARE @db   sysname;
DECLARE @dbid int;
DECLARE @sql  nvarchar(max);

DECLARE db_cur CURSOR LOCAL FAST_FORWARD FOR
    SELECT name FROM sys.databases
    WHERE state_desc = |ONLINE| AND database_id > 4 AND is_read_only = 0;

OPEN db_cur;
FETCH NEXT FROM db_cur INTO @db;

WHILE @@FETCH_STATUS = 0
BEGIN
    SET @dbid = DB_ID(@db);
    SET @sql =
        N|INSERT INTO [<<DB>>].[collector].[IndexFragmentation] |
      + N|(server_name, collection_time, database_name, schema_name, table_name, |
      + N|index_name, index_type, partition_number, page_count, |
      + N|avg_fragmentation_pct, fragment_count, avg_fragment_size_pages, recommended_action) |
      + N|SELECT @@SERVERNAME, GETDATE(), DB_NAME(| + CAST(@dbid AS nvarchar(10)) + N|), |
      + N|s.name, o.name, ix.name, ix.type_desc, |
      + N|ips.partition_number, ips.page_count, |
      + N|CAST(ips.avg_fragmentation_in_percent AS decimal(5,1)), |
      + N|ips.fragment_count, CAST(ips.avg_fragment_size_in_pages AS decimal(8,1)), |
      + N|CASE |
      + N|    WHEN ips.avg_fragmentation_in_percent >= 30 THEN ||REBUILD|| |
      + N|    WHEN ips.avg_fragmentation_in_percent >= 10 THEN ||REORGANIZE|| |
      + N|    ELSE ||NONE|| |
      + N|END |
      + N|FROM sys.dm_db_index_physical_stats(| + CAST(@dbid AS nvarchar(10)) + N|, NULL, NULL, NULL, ||SAMPLED||) ips |
      + N|JOIN [| + @db + N|].sys.indexes  ix ON ix.object_id = ips.object_id AND ix.index_id = ips.index_id |
      + N|JOIN [| + @db + N|].sys.objects  o  ON o.object_id  = ips.object_id |
      + N|JOIN [| + @db + N|].sys.schemas  s  ON s.schema_id  = o.schema_id |
      + N|WHERE ips.page_count >= 100 AND ips.index_id > 0 AND o.is_ms_shipped = 0;|;

    BEGIN TRY
        EXEC sp_executesql @sql;
    END TRY
    BEGIN CATCH
        -- Skip inaccessible or incompatible databases
    END CATCH;

    FETCH NEXT FROM db_cur INTO @db;
END;
CLOSE db_cur;
DEALLOCATE db_cur;'
, N'|', NCHAR(39));

SET @stepCmd = REPLACE(@stepCmd, N'<<DB>>', @TargetDatabase);

-- ═══════════════════════════════════════════════════════════════════════════════
-- DDL output
-- ═══════════════════════════════════════════════════════════════════════════════
SET @ddl =
    N'-- ================================================================' + @crlf +
    N'-- Generated by Generate-CollectorJob-IndexFragmentation.sql'        + @crlf +
    N'-- Server    : ' + @@SERVERNAME                                      + @crlf +
    N'-- Target DB : ' + @TargetDatabase                                   + @crlf +
    N'-- Generated : ' + CONVERT(nvarchar(20), GETDATE(), 120)             + @crlf +
    N'-- ================================================================' + @crlf + @crlf;

-- ── 1. Target database ────────────────────────────────────────────────────────
SET @ddl +=
    N'IF NOT EXISTS (SELECT 1 FROM sys.databases WHERE name = N' + @q + @TargetDatabase + @q + N')' + @crlf +
    N'    CREATE DATABASE [' + @TargetDatabase + N'];'                                               + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 2. Collector schema ───────────────────────────────────────────────────────
SET @ddl +=
    N'IF NOT EXISTS (SELECT 1 FROM [' + @TargetDatabase + N'].sys.schemas WHERE name = N' + @q + N'collector' + @q + N')' + @crlf +
    N'    EXEC [' + @TargetDatabase + N'].sys.sp_executesql N' + @q + N'CREATE SCHEMA collector' + @q + N';'              + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 3. IndexFragmentation table ───────────────────────────────────────────────
SET @ddl +=
    N'IF NOT EXISTS (' + @crlf +
    N'    SELECT 1 FROM [' + @TargetDatabase + N'].sys.objects o'                                                              + @crlf +
    N'    JOIN [' + @TargetDatabase + N'].sys.schemas s ON s.schema_id = o.schema_id'                                         + @crlf +
    N'    WHERE o.name = N' + @q + N'IndexFragmentation' + @q + N' AND s.name = N' + @q + N'collector' + @q + N')'          + @crlf +
    N'CREATE TABLE [' + @TargetDatabase + N'].[collector].[IndexFragmentation] ('                                              + @crlf +
    N'    id                       bigint IDENTITY(1,1) PRIMARY KEY,'                                                          + @crlf +
    N'    server_name              nvarchar(128) NOT NULL,'                                                                     + @crlf +
    N'    collection_time          datetime2     NOT NULL,'                                                                     + @crlf +
    N'    database_name            nvarchar(128),'                                                                              + @crlf +
    N'    schema_name              nvarchar(128),'                                                                              + @crlf +
    N'    table_name               nvarchar(128),'                                                                              + @crlf +
    N'    index_name               nvarchar(128),'                                                                              + @crlf +
    N'    index_type               nvarchar(60),'                                                                               + @crlf +
    N'    partition_number         int,'                                                                                        + @crlf +
    N'    page_count               bigint,'                                                                                     + @crlf +
    N'    avg_fragmentation_pct    decimal(5,1),'                                                                               + @crlf +
    N'    fragment_count           bigint,'                                                                                     + @crlf +
    N'    avg_fragment_size_pages  decimal(8,1),'                                                                               + @crlf +
    N'    recommended_action       nvarchar(20)'                                                                                + @crlf +
    N');'                                                                                                                       + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 4. Agent category ─────────────────────────────────────────────────────────
SET @ddl +=
    N'USE msdb;' + @crlf +
    N'GO' + @crlf + @crlf +
    N'IF NOT EXISTS (SELECT 1 FROM msdb.dbo.syscategories WHERE name = N' + @q + @CategoryName + @q + N' AND category_class = 1)' + @crlf +
    N'    EXEC msdb.dbo.sp_add_category'                                                                                             + @crlf +
    N'        @class = N' + @q + N'JOB' + @q + N', @type = N' + @q + N'LOCAL' + @q + N', @name = N' + @q + @CategoryName + @q + N';' + @crlf +
    N'GO' + @crlf + @crlf;

-- ── 5. Job + step + schedule (weekly Saturday at @RunHour:00) ─────────────────
SET @ddl +=
    N'-- Job: ' + @jobName + @crlf +
    N'IF EXISTS (SELECT 1 FROM msdb.dbo.sysjobs WHERE name = N' + @q + @jobName + @q + N')' + @crlf +
    N'    EXEC msdb.dbo.sp_delete_job @job_name = N' + @q + @jobName + @q + N', @delete_unused_schedule = 1;' + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_job'                                                    + @crlf +
    N'    @job_name         = N' + @q + @jobName + @q + N','                       + @crlf +
    N'    @enabled          = 1,'                                                   + @crlf +
    N'    @owner_login_name = N' + @q + @JobOwner + @q + N','                      + @crlf +
    N'    @category_name    = N' + @q + @CategoryName + @q + N';'                  + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_jobstep'                                                + @crlf +
    N'    @job_name          = N' + @q + @jobName + @q + N','                      + @crlf +
    N'    @step_id           = 1,'                                                  + @crlf +
    N'    @step_name         = N' + @q + N'Snapshot index fragmentation all databases' + @q + N',' + @crlf +
    N'    @subsystem         = N' + @q + N'TSQL' + @q + N','                       + @crlf +
    N'    @database_name     = N' + @q + N'master' + @q + N','                     + @crlf +
    N'    @command           = N' + @q + REPLACE(@stepCmd, @q, @q + @q) + @q + N',' + @crlf +
    N'    @retry_attempts    = 0,'                                                  + @crlf +
    N'    @on_success_action = 1,'                                                  + @crlf +
    N'    @on_fail_action    = 2;'                                                  + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_schedule'                                               + @crlf +
    N'    @schedule_name          = N' + @q + @jobName + N' Weekly Sat ' + CAST(@RunHour AS nvarchar(2)) + N':00' + @q + N',' + @crlf +
    N'    @freq_type              = 8,'                                             + @crlf +   -- weekly
    N'    @freq_interval          = 64,'                                            + @crlf +   -- Saturday
    N'    @freq_recurrence_factor = 1,'                                             + @crlf +
    N'    @active_start_time      = ' + CAST(@schedTS AS nvarchar(10)) + N';'      + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_attach_schedule'                                            + @crlf +
    N'    @job_name      = N' + @q + @jobName + @q + N','                          + @crlf +
    N'    @schedule_name = N' + @q + @jobName + N' Weekly Sat ' + CAST(@RunHour AS nvarchar(2)) + N':00' + @q + N';' + @crlf + @crlf +

    N'EXEC msdb.dbo.sp_add_jobserver @job_name = N' + @q + @jobName + @q + N';'   + @crlf +
    N'GO' + @crlf;

SELECT @ddl AS ddl;
