/*
Script Name : Generate-MaintenanceJobs
Category    : maintenance
Purpose     : Generates SQL Agent DDL for routine housekeeping jobs:
              DBA - Integrity Check   DBCC CHECKDB on all online user databases (weekly)
              DBA - History Cleanup   purges msdb backup history, job history, and
                                      Database Mail log based on retention periods (weekly)
              DBA - Cycle Error Log   sp_cycle_errorlog to rotate the SQL Server error log
                                      and prevent it growing unbounded (weekly)
              Edit the parameters section, review the output, then run on the target instance.
Author      : Peter Whyte (https://sqldba.blog)
Requires    : VIEW ANY DATABASE
Notes       : DBCC CHECKDB is resource-intensive. Schedule on a quiet period.
              On a large estate, consider reducing to monthly or running per-filegroup.
              History Cleanup deletes msdb rows permanently — retention periods are minimums.
*/
-- SAFE:ReadOnly
-- IMPACT:Low
SET NOCOUNT ON;

-- ── Parameters ────────────────────────────────────────────────────────────────
DECLARE @BackupHistoryDays  int           = 90;     -- backup/restore history kept this many days
DECLARE @JobHistoryDays     int           = 30;     -- job history records kept this many days
DECLARE @CheckDbHour        tinyint       = 2;      -- hour (0-23) for weekly integrity check
DECLARE @CleanupHour        tinyint       = 3;      -- hour (0-23) for weekly history cleanup
DECLARE @CycleLogHour       tinyint       = 0;      -- hour (0-23) for weekly error log cycle
DECLARE @JobOwner           sysname       = N'sa';
DECLARE @CategoryName       nvarchar(128) = N'Database Maintenance';
-- ─────────────────────────────────────────────────────────────────────────────

DECLARE @q              nchar(1)      = NCHAR(39);
DECLARE @crlf           nvarchar(2)   = CHAR(13) + CHAR(10);
DECLARE @ddl            nvarchar(max) = N'';
DECLARE @checkSchedTS   int           = @CheckDbHour  * 10000;
DECLARE @cleanSchedTS   int           = @CleanupHour  * 10000;
DECLARE @cycleSchedTS   int           = @CycleLogHour * 10000;

-- ── Step command: DBCC CHECKDB ────────────────────────────────────────────────
DECLARE @checkCmd nvarchar(max) = REPLACE(
N'SET NOCOUNT ON;
DECLARE @db sysname, @sql nvarchar(max);
DECLARE c CURSOR LOCAL FAST_FORWARD FOR
    SELECT name FROM sys.databases
    WHERE database_id > 4 AND state_desc = N|ONLINE| AND is_read_only = 0
    ORDER BY name;
OPEN c;
FETCH NEXT FROM c INTO @db;
WHILE @@FETCH_STATUS = 0
BEGIN
    SET @sql = N|DBCC CHECKDB ([| + @db + N|]) WITH NO_INFOMSGS, ALL_ERRORMSGS;|;
    EXEC sp_executesql @sql;
    FETCH NEXT FROM c INTO @db;
END
CLOSE c;
DEALLOCATE c;'
, N'|', NCHAR(39));

-- ── Step command: history cleanup ─────────────────────────────────────────────
DECLARE @cleanCmd nvarchar(max) = REPLACE(
N'SET NOCOUNT ON;

-- Purge backup and restore history
EXEC msdb.dbo.sp_delete_backuphistory
    @oldest_date = DATEADD(DAY, -<<BACKUP_DAYS>>, GETDATE());

-- Purge SQL Agent job history
EXEC msdb.dbo.sp_purge_jobhistory
    @oldest_date = DATEADD(DAY, -<<JOB_DAYS>>, GETDATE());

-- Purge Database Mail items and log (only if Database Mail is configured)
IF EXISTS (SELECT 1 FROM msdb.dbo.sysmail_profile)
BEGIN
    EXEC msdb.dbo.sysmail_delete_mailitems_sp
        @sent_before = DATEADD(DAY, -<<JOB_DAYS>>, GETDATE());
    EXEC msdb.dbo.sysmail_delete_log_sp
        @logged_before = DATEADD(DAY, -<<JOB_DAYS>>, GETDATE());
END'
, N'|', NCHAR(39));

SET @cleanCmd = REPLACE(@cleanCmd, N'<<BACKUP_DAYS>>', CAST(@BackupHistoryDays AS nvarchar(5)));
SET @cleanCmd = REPLACE(@cleanCmd, N'<<JOB_DAYS>>',    CAST(@JobHistoryDays    AS nvarchar(5)));

-- ── Step command: cycle error log ────────────────────────────────────────────
DECLARE @cycleCmd nvarchar(max) = N'EXEC sp_cycle_errorlog;';

-- ═══════════════════════════════════════════════════════════════════════════
-- DDL output
-- ═══════════════════════════════════════════════════════════════════════════
SET @ddl =
    N'-- =================================================================' + @crlf +
    N'-- Generated by Generate-MaintenanceJobs.sql' + @crlf +
    N'-- Server              : ' + @@SERVERNAME + @crlf +
    N'-- Backup history kept : ' + CAST(@BackupHistoryDays AS nvarchar(5)) + N' days' + @crlf +
    N'-- Job history kept    : ' + CAST(@JobHistoryDays    AS nvarchar(5)) + N' days' + @crlf +
    N'-- Generated           : ' + CONVERT(nvarchar(20), GETDATE(), 120) + @crlf +
    N'-- =================================================================' + @crlf +
    @crlf +
    N'USE msdb;' + @crlf +
    N'GO' + @crlf;

-- Category
SET @ddl +=
    @crlf +
    N'IF NOT EXISTS (SELECT 1 FROM msdb.dbo.syscategories' + @crlf +
    N'               WHERE name = N' + @q + @CategoryName + @q + N' AND category_class = 1)' + @crlf +
    N'    EXEC msdb.dbo.sp_add_category' + @crlf +
    N'        @class = N' + @q + N'JOB' + @q + N', @type = N' + @q + N'LOCAL' + @q
        + N', @name = N' + @q + @CategoryName + @q + N';' + @crlf +
    N'GO' + @crlf;

-- ── Job 1: DBA - Integrity Check ──────────────────────────────────────────────
SET @ddl +=
    @crlf +
    N'-- ==================================================================' + @crlf +
    N'-- Job: DBA - Integrity Check' + @crlf +
    N'-- Schedule: weekly, Saturday at ' + CAST(@CheckDbHour AS nvarchar(2)) + N':00' + @crlf +
    N'-- ==================================================================' + @crlf +
    N'IF EXISTS (SELECT 1 FROM msdb.dbo.sysjobs WHERE name = N' + @q + N'DBA - Integrity Check' + @q + N')' + @crlf +
    N'    EXEC msdb.dbo.sp_delete_job' + @crlf +
    N'        @job_name              = N' + @q + N'DBA - Integrity Check' + @q + N',' + @crlf +
    N'        @delete_unused_schedule = 1;' + @crlf +
    @crlf +
    N'EXEC msdb.dbo.sp_add_job' + @crlf +
    N'    @job_name          = N' + @q + N'DBA - Integrity Check' + @q + N',' + @crlf +
    N'    @enabled           = 1,' + @crlf +
    N'    @owner_login_name  = N' + @q + @JobOwner + @q + N',' + @crlf +
    N'    @category_name     = N' + @q + @CategoryName + @q + N';' + @crlf +
    @crlf +
    N'EXEC msdb.dbo.sp_add_jobstep' + @crlf +
    N'    @job_name          = N' + @q + N'DBA - Integrity Check' + @q + N',' + @crlf +
    N'    @step_id           = 1,' + @crlf +
    N'    @step_name         = N' + @q + N'DBCC CHECKDB all user databases' + @q + N',' + @crlf +
    N'    @subsystem         = N' + @q + N'TSQL' + @q + N',' + @crlf +
    N'    @database_name     = N' + @q + N'master' + @q + N',' + @crlf +
    N'    @command           = N' + @q + REPLACE(@checkCmd, @q, @q + @q) + @q + N',' + @crlf +
    N'    @retry_attempts    = 0,' + @crlf +
    N'    @on_success_action = 1,' + @crlf +
    N'    @on_fail_action    = 2;' + @crlf +
    @crlf +
    N'EXEC msdb.dbo.sp_add_schedule' + @crlf +
    N'    @schedule_name          = N' + @q + N'DBA - Integrity Check Weekly Sat '
        + CAST(@CheckDbHour AS nvarchar(2)) + N':00' + @q + N',' + @crlf +
    N'    @freq_type              = 8,' + @crlf +
    N'    @freq_interval          = 64,' + @crlf +   -- 64 = Saturday
    N'    @freq_recurrence_factor = 1,' + @crlf +
    N'    @active_start_time      = ' + CAST(@checkSchedTS AS nvarchar(10)) + N';' + @crlf +
    @crlf +
    N'EXEC msdb.dbo.sp_attach_schedule' + @crlf +
    N'    @job_name      = N' + @q + N'DBA - Integrity Check' + @q + N',' + @crlf +
    N'    @schedule_name = N' + @q + N'DBA - Integrity Check Weekly Sat '
        + CAST(@CheckDbHour AS nvarchar(2)) + N':00' + @q + N';' + @crlf +
    @crlf +
    N'EXEC msdb.dbo.sp_add_jobserver @job_name = N' + @q + N'DBA - Integrity Check' + @q + N';' + @crlf +
    N'GO' + @crlf;

-- ── Job 2: DBA - History Cleanup ──────────────────────────────────────────────
SET @ddl +=
    @crlf +
    N'-- ==================================================================' + @crlf +
    N'-- Job: DBA - History Cleanup' + @crlf +
    N'-- Schedule: weekly, Sunday at ' + CAST(@CleanupHour AS nvarchar(2)) + N':00' + @crlf +
    N'-- ==================================================================' + @crlf +
    N'IF EXISTS (SELECT 1 FROM msdb.dbo.sysjobs WHERE name = N' + @q + N'DBA - History Cleanup' + @q + N')' + @crlf +
    N'    EXEC msdb.dbo.sp_delete_job' + @crlf +
    N'        @job_name              = N' + @q + N'DBA - History Cleanup' + @q + N',' + @crlf +
    N'        @delete_unused_schedule = 1;' + @crlf +
    @crlf +
    N'EXEC msdb.dbo.sp_add_job' + @crlf +
    N'    @job_name          = N' + @q + N'DBA - History Cleanup' + @q + N',' + @crlf +
    N'    @enabled           = 1,' + @crlf +
    N'    @owner_login_name  = N' + @q + @JobOwner + @q + N',' + @crlf +
    N'    @category_name     = N' + @q + @CategoryName + @q + N';' + @crlf +
    @crlf +
    N'EXEC msdb.dbo.sp_add_jobstep' + @crlf +
    N'    @job_name          = N' + @q + N'DBA - History Cleanup' + @q + N',' + @crlf +
    N'    @step_id           = 1,' + @crlf +
    N'    @step_name         = N' + @q + N'Purge backup history, job history, and mail log' + @q + N',' + @crlf +
    N'    @subsystem         = N' + @q + N'TSQL' + @q + N',' + @crlf +
    N'    @database_name     = N' + @q + N'msdb' + @q + N',' + @crlf +
    N'    @command           = N' + @q + REPLACE(@cleanCmd, @q, @q + @q) + @q + N',' + @crlf +
    N'    @retry_attempts    = 0,' + @crlf +
    N'    @on_success_action = 1,' + @crlf +
    N'    @on_fail_action    = 2;' + @crlf +
    @crlf +
    N'EXEC msdb.dbo.sp_add_schedule' + @crlf +
    N'    @schedule_name          = N' + @q + N'DBA - History Cleanup Weekly Sun '
        + CAST(@CleanupHour AS nvarchar(2)) + N':00' + @q + N',' + @crlf +
    N'    @freq_type              = 8,' + @crlf +
    N'    @freq_interval          = 1,' + @crlf +    -- 1 = Sunday
    N'    @freq_recurrence_factor = 1,' + @crlf +
    N'    @active_start_time      = ' + CAST(@cleanSchedTS AS nvarchar(10)) + N';' + @crlf +
    @crlf +
    N'EXEC msdb.dbo.sp_attach_schedule' + @crlf +
    N'    @job_name      = N' + @q + N'DBA - History Cleanup' + @q + N',' + @crlf +
    N'    @schedule_name = N' + @q + N'DBA - History Cleanup Weekly Sun '
        + CAST(@CleanupHour AS nvarchar(2)) + N':00' + @q + N';' + @crlf +
    @crlf +
    N'EXEC msdb.dbo.sp_add_jobserver @job_name = N' + @q + N'DBA - History Cleanup' + @q + N';' + @crlf +
    N'GO' + @crlf;

-- ── Job 3: DBA - Cycle Error Log ──────────────────────────────────────────────
SET @ddl +=
    @crlf +
    N'-- ==================================================================' + @crlf +
    N'-- Job: DBA - Cycle Error Log' + @crlf +
    N'-- Schedule: weekly, Monday at ' + CAST(@CycleLogHour AS nvarchar(2)) + N':00' + @crlf +
    N'-- Rotates the SQL Server error log; keeps last 6 archived logs by default.' + @crlf +
    N'-- To increase archived log count: HKLM\SOFTWARE\Microsoft\MSSQLServer\MSSQLServer\NumErrorLogs' + @crlf +
    N'-- ==================================================================' + @crlf +
    N'IF EXISTS (SELECT 1 FROM msdb.dbo.sysjobs WHERE name = N' + @q + N'DBA - Cycle Error Log' + @q + N')' + @crlf +
    N'    EXEC msdb.dbo.sp_delete_job' + @crlf +
    N'        @job_name              = N' + @q + N'DBA - Cycle Error Log' + @q + N',' + @crlf +
    N'        @delete_unused_schedule = 1;' + @crlf +
    @crlf +
    N'EXEC msdb.dbo.sp_add_job' + @crlf +
    N'    @job_name          = N' + @q + N'DBA - Cycle Error Log' + @q + N',' + @crlf +
    N'    @enabled           = 1,' + @crlf +
    N'    @owner_login_name  = N' + @q + @JobOwner + @q + N',' + @crlf +
    N'    @category_name     = N' + @q + @CategoryName + @q + N';' + @crlf +
    @crlf +
    N'EXEC msdb.dbo.sp_add_jobstep' + @crlf +
    N'    @job_name          = N' + @q + N'DBA - Cycle Error Log' + @q + N',' + @crlf +
    N'    @step_id           = 1,' + @crlf +
    N'    @step_name         = N' + @q + N'Cycle error log' + @q + N',' + @crlf +
    N'    @subsystem         = N' + @q + N'TSQL' + @q + N',' + @crlf +
    N'    @database_name     = N' + @q + N'master' + @q + N',' + @crlf +
    N'    @command           = N' + @q + REPLACE(@cycleCmd, @q, @q + @q) + @q + N',' + @crlf +
    N'    @retry_attempts    = 0,' + @crlf +
    N'    @on_success_action = 1,' + @crlf +
    N'    @on_fail_action    = 2;' + @crlf +
    @crlf +
    N'EXEC msdb.dbo.sp_add_schedule' + @crlf +
    N'    @schedule_name          = N' + @q + N'DBA - Cycle Error Log Weekly Mon '
        + CAST(@CycleLogHour AS nvarchar(2)) + N':00' + @q + N',' + @crlf +
    N'    @freq_type              = 8,' + @crlf +
    N'    @freq_interval          = 2,' + @crlf +    -- 2 = Monday
    N'    @freq_recurrence_factor = 1,' + @crlf +
    N'    @active_start_time      = ' + CAST(@cycleSchedTS AS nvarchar(10)) + N';' + @crlf +
    @crlf +
    N'EXEC msdb.dbo.sp_attach_schedule' + @crlf +
    N'    @job_name      = N' + @q + N'DBA - Cycle Error Log' + @q + N',' + @crlf +
    N'    @schedule_name = N' + @q + N'DBA - Cycle Error Log Weekly Mon '
        + CAST(@CycleLogHour AS nvarchar(2)) + N':00' + @q + N';' + @crlf +
    @crlf +
    N'EXEC msdb.dbo.sp_add_jobserver @job_name = N' + @q + N'DBA - Cycle Error Log' + @q + N';' + @crlf +
    N'GO' + @crlf;

SELECT @ddl AS ddl;
